/**
 * VITALIS - Comprehensive Indian Food & Recipe Database Seed
 * Sources:
 * 1. Anuvaad Indian Nutrient Databank (INDB) (https://www.anuvaad.org.in/)
 * 2. ICMR-NIN Indian Food Composition Tables (IFCT 2017)
 * 
 * Fields: name, category, portion_description, base_amount, base_unit, calories, protein, carbs, fat, fiber
 * System foods: user_id = NULL
 */

const fs = require('fs');
const path = require('path');
const csvx = require('csv-parse/sync');
const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || 'https://zqraxlkfiqgaecdslkzu.supabase.co';
const SUPABASE_KEY = process.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_UKmol7CuOwTz3OMqvPRocw_8X7c2flJ';
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

// 1. Group Mapping for IFCT categories
const GROUP_CATEGORY_MAP = {
  'Cereals and Millets': 'Cereals and Millets',
  'Grain Legumes': 'Grain Legumes and Pulses',
  'Green Leafy Vegetables': 'Green Leafy Vegetables',
  'Other Vegetables': 'Vegetables and Sabzi',
  'Fruits': 'Fruits and Fruit Juices',
  'Roots and Tubers': 'Vegetables and Sabzi',
  'Condiments and Spices': 'Condiments and Spices',
  'Nuts and Oilseeds': 'Nuts and Oilseeds',
  'Milk and Milk Products': 'Dairy and Beverages',
  'Meat and Poultry': 'Meat and Poultry',
  'Fish and Other Sea Foods': 'Fish and Seafood',
  'Sugars': 'Indian Sweets and Mithai',
  'Fats and Edible Oils': 'Fats and Oils',
  'Miscellaneous': 'Snacks and Chaat',
};

// 2. Format localized names nicely
function extractPopularAliases(langStr) {
  if (!langStr) return '';
  const aliases = [];
  const parts = langStr.split(';');
  for (const p of parts) {
    const trimmed = p.trim();
    if (!trimmed) continue;
    const match = trimmed.match(/^(?:A|B|G|H|Kan|Kash|Mal|M|Mar|N|O|P|Tam|Tel|U|S|Kh|E)\.\s*([^,\[\(\.\;]+)/i);
    if (match && match[1]) {
      const name = match[1].trim();
      if (name && !aliases.includes(name) && aliases.length < 4) {
        aliases.push(name);
      }
    }
  }
  return aliases.join(', ');
}

// 3. Extract IFCT raw foods
function getIFCTFoods() {
  const compCsvPath = path.join(__dirname, '../../node_modules/@ifct2017/compositions/index.csv');
  const content = fs.readFileSync(compCsvPath, 'utf8');

  const records = csvx.parse(content, {
    columns: true,
    skip_empty_lines: true,
    comment: '#',
  });

  const getCol = (row, field) => {
    for (const k of Object.keys(row)) {
      if (k.endsWith(`; ${field}`) || k === field) {
        return row[k];
      }
    }
    return '';
  };

  const foods = [];

  for (const row of records) {
    const code = getCol(row, 'code');
    const rawName = getCol(row, 'name');
    const langStr = getCol(row, 'lang');
    const grup = getCol(row, 'grup');
    const enerc = parseFloat(getCol(row, 'enerc')) || 0; // in kJ
    const prot = parseFloat(getCol(row, 'protcnt')) || 0;
    const fat = parseFloat(getCol(row, 'fatce')) || 0;
    const carbs = parseFloat(getCol(row, 'choavldf')) || 0;
    const fiber = parseFloat(getCol(row, 'fibtg')) || 0;

    // Convert kJ to kcal (standard 4.184 kJ/kcal)
    const kcal = Math.round(enerc / 4.184);

    const aliases = extractPopularAliases(langStr);
    let displayName = rawName;
    if (aliases) {
      displayName = `${rawName} (${aliases})`;
    }

    const category = GROUP_CATEGORY_MAP[grup] || 'Vegetables and Sabzi';
    let portion = '100g raw / edible portion';
    if (category.includes('Milk') || category.includes('Dairy')) {
      portion = '100ml / 100g';
    } else if (category.includes('Spices') || category.includes('Fats')) {
      portion = '1 tablespoon (15g)';
    }

    foods.push({
      name: displayName,
      category,
      portion_description: portion,
      base_amount: 100,
      base_unit: 'g',
      calories: kcal,
      protein: Math.round(prot * 10) / 10,
      carbs: Math.round(carbs * 10) / 10,
      fat: Math.round(fat * 10) / 10,
      fiber: Math.round(fiber * 10) / 10,
    });
  }

  return foods;
}

// 4. Curated Anuvaad Indian Cooked Dishes & Recipes
const anuvaadCookedFoods = [
  // BREAKFAST FOODS & TIFFIN
  {
    name: 'Idli (Steamed Rice & Urad Dal Cake)',
    category: 'Breakfast foods',
    portion_description: '2 medium idlis (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 142,
    protein: 4.8,
    carbs: 28.5,
    fat: 0.4,
    fiber: 1.8,
  },
  {
    name: 'Rava Idli',
    category: 'Breakfast foods',
    portion_description: '2 medium idlis (90g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 168,
    protein: 4.2,
    carbs: 29.8,
    fat: 3.4,
    fiber: 1.5,
  },
  {
    name: 'Plain Dosa',
    category: 'Breakfast foods',
    portion_description: '1 medium dosa (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 168,
    protein: 3.9,
    carbs: 29.2,
    fat: 3.8,
    fiber: 1.6,
  },
  {
    name: 'Masala Dosa (with Potato Filling)',
    category: 'Breakfast foods',
    portion_description: '1 dosa with potato masala (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 185,
    protein: 3.8,
    carbs: 28.4,
    fat: 6.2,
    fiber: 2.1,
  },
  {
    name: 'Ghee Roast Dosa',
    category: 'Breakfast foods',
    portion_description: '1 large crispy dosa (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 235,
    protein: 4.1,
    carbs: 30.5,
    fat: 10.8,
    fiber: 1.5,
  },
  {
    name: 'Rava Dosa (Onion & Semolina)',
    category: 'Breakfast foods',
    portion_description: '1 large thin dosa (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 196,
    protein: 4.2,
    carbs: 32.6,
    fat: 5.4,
    fiber: 1.7,
  },
  {
    name: 'Pesarattu (Green Moong Dosa)',
    category: 'Breakfast foods',
    portion_description: '1 medium dosa (90g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 154,
    protein: 8.4,
    carbs: 23.2,
    fat: 2.8,
    fiber: 4.2,
  },
  {
    name: 'Neer Dosa',
    category: 'Breakfast foods',
    portion_description: '2 soft thin dosas (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 138,
    protein: 2.6,
    carbs: 28.8,
    fat: 1.2,
    fiber: 0.8,
  },
  {
    name: 'Adai (High-Protein Mixed Lentil & Rice Crepe)',
    category: 'Breakfast foods',
    portion_description: '1 medium adai (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 184,
    protein: 8.6,
    carbs: 26.4,
    fat: 5.2,
    fiber: 4.8,
  },
  {
    name: 'Medu Vada (Fried Lentil Fritter)',
    category: 'Breakfast foods',
    portion_description: '1 piece (45g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 278,
    protein: 9.8,
    carbs: 28.6,
    fat: 13.8,
    fiber: 4.5,
  },
  {
    name: 'Masala Vada (Chana Dal Crispy Fritter)',
    category: 'Breakfast foods',
    portion_description: '1 piece (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 295,
    protein: 11.2,
    carbs: 31.4,
    fat: 14.2,
    fiber: 5.6,
  },
  {
    name: 'Onion Tomato Uttapam',
    category: 'Breakfast foods',
    portion_description: '1 medium uttapam (130g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 172,
    protein: 4.2,
    carbs: 27.8,
    fat: 4.8,
    fiber: 2.3,
  },
  {
    name: 'Kuzhi Paniyaram (Crispy Rice & Lentil Dumplings)',
    category: 'Breakfast foods',
    portion_description: '4 pieces (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 172,
    protein: 4.2,
    carbs: 28.6,
    fat: 4.6,
    fiber: 2.1,
  },
  {
    name: 'Ven Pongal (Ghee & Moong Dal Rice)',
    category: 'Breakfast foods',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 178,
    protein: 4.8,
    carbs: 24.6,
    fat: 6.8,
    fiber: 2.2,
  },
  {
    name: 'Poha (Flattened Rice with Peanuts & Potatoes)',
    category: 'Breakfast foods',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 162,
    protein: 3.4,
    carbs: 27.8,
    fat: 4.1,
    fiber: 2.4,
  },
  {
    name: 'Upma (Semolina/Rava with Vegetables)',
    category: 'Breakfast foods',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 148,
    protein: 3.8,
    carbs: 24.2,
    fat: 3.9,
    fiber: 1.8,
  },
  {
    name: 'Semiya Upma (Vermicelli)',
    category: 'Breakfast foods',
    portion_description: '1 bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 156,
    protein: 3.6,
    carbs: 26.5,
    fat: 3.8,
    fiber: 1.5,
  },
  {
    name: 'Sabudana Khichdi (Tapioca Pearls with Peanuts)',
    category: 'Breakfast foods',
    portion_description: '1 bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 228,
    protein: 3.2,
    carbs: 38.6,
    fat: 6.9,
    fiber: 1.6,
  },
  {
    name: 'Besan Chilla (Gram Flour Pancake)',
    category: 'Breakfast foods',
    portion_description: '1 chilla (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 172,
    protein: 8.8,
    carbs: 21.4,
    fat: 5.6,
    fiber: 4.8,
  },
  {
    name: 'Moong Dal Chilla (Yellow Lentil Crepe)',
    category: 'Breakfast foods',
    portion_description: '1 chilla (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 158,
    protein: 9.6,
    carbs: 22.8,
    fat: 3.2,
    fiber: 4.1,
  },
  {
    name: 'Appam (Fermented Rice Pancake)',
    category: 'Breakfast foods',
    portion_description: '1 piece (60g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 132,
    protein: 2.2,
    carbs: 27.6,
    fat: 1.2,
    fiber: 0.8,
  },
  {
    name: 'Puttu (Steamed Rice & Coconut Cake)',
    category: 'Breakfast foods',
    portion_description: '1 cylinder slice (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 186,
    protein: 3.8,
    carbs: 34.2,
    fat: 3.6,
    fiber: 2.1,
  },
  {
    name: 'Idiyappam (String Hoppers)',
    category: 'Breakfast foods',
    portion_description: '3 small nests (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 124,
    protein: 2.4,
    carbs: 27.2,
    fat: 0.4,
    fiber: 0.9,
  },
  {
    name: 'Dhokla (Khaman Steamed Gram Flour)',
    category: 'Breakfast foods',
    portion_description: '2 squares (70g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 152,
    protein: 6.8,
    carbs: 22.4,
    fat: 3.8,
    fiber: 3.2,
  },
  {
    name: 'Khandvi',
    category: 'Breakfast foods',
    portion_description: '4 rolled pieces (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 146,
    protein: 5.6,
    carbs: 18.2,
    fat: 5.4,
    fiber: 2.4,
  },
  {
    name: 'Khichu (Steamed Rice Flour Snack with Cumin & Oil)',
    category: 'Breakfast foods',
    portion_description: '1 bowl (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 142,
    protein: 2.4,
    carbs: 26.8,
    fat: 2.8,
    fiber: 1.2,
  },
  {
    name: 'Misal Pav (Spiced Sprouted Curry with Bread)',
    category: 'Breakfast foods',
    portion_description: '1 serving with 2 pavs (280g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 184,
    protein: 6.2,
    carbs: 26.5,
    fat: 5.9,
    fiber: 3.8,
  },

  // ROTI, CHAPATI, PARATHA & BREADS
  {
    name: 'Phulka / Roti (Dry Whole Wheat, No Oil)',
    category: 'Roti and Indian Breads',
    portion_description: '1 medium roti (35g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 264,
    protein: 9.4,
    carbs: 52.8,
    fat: 1.2,
    fiber: 8.6,
  },
  {
    name: 'Chapati (with Light Ghee / Oil)',
    category: 'Roti and Indian Breads',
    portion_description: '1 medium chapati (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 298,
    protein: 8.8,
    carbs: 49.2,
    fat: 6.8,
    fiber: 7.8,
  },
  {
    name: 'Plain Paratha (Layered Whole Wheat)',
    category: 'Roti and Indian Breads',
    portion_description: '1 medium paratha (60g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 326,
    protein: 7.6,
    carbs: 46.8,
    fat: 11.8,
    fiber: 6.4,
  },
  {
    name: 'Aloo Paratha (Spiced Potato Stuffed)',
    category: 'Roti and Indian Breads',
    portion_description: '1 stuffed paratha (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 242,
    protein: 5.4,
    carbs: 37.6,
    fat: 7.8,
    fiber: 4.2,
  },
  {
    name: 'Paneer Paratha (Cottage Cheese Stuffed)',
    category: 'Roti and Indian Breads',
    portion_description: '1 stuffed paratha (130g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 278,
    protein: 10.8,
    carbs: 32.4,
    fat: 11.2,
    fiber: 3.8,
  },
  {
    name: 'Gobi Paratha (Cauliflower Stuffed)',
    category: 'Roti and Indian Breads',
    portion_description: '1 stuffed paratha (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 224,
    protein: 6.2,
    carbs: 34.8,
    fat: 6.8,
    fiber: 4.6,
  },
  {
    name: 'Methi Thepla (Fenugreek & Spiced Flatbread)',
    category: 'Roti and Indian Breads',
    portion_description: '1 thepla (45g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 295,
    protein: 8.6,
    carbs: 47.4,
    fat: 7.8,
    fiber: 7.2,
  },
  {
    name: 'Bajra Roti (Pearl Millet Flatbread)',
    category: 'Roti and Indian Breads',
    portion_description: '1 medium roti (60g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 248,
    protein: 7.8,
    carbs: 49.2,
    fat: 2.2,
    fiber: 8.8,
  },
  {
    name: 'Jowar Roti / Bhakri (Sorghum Flatbread)',
    category: 'Roti and Indian Breads',
    portion_description: '1 medium bhakri (65g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 242,
    protein: 7.2,
    carbs: 51.4,
    fat: 1.6,
    fiber: 7.9,
  },
  {
    name: 'Ragi Roti (Finger Millet Flatbread)',
    category: 'Roti and Indian Breads',
    portion_description: '1 medium roti (60g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 236,
    protein: 6.4,
    carbs: 48.6,
    fat: 1.8,
    fiber: 9.4,
  },
  {
    name: 'Tandoori Roti (Whole Wheat, Clay Oven)',
    category: 'Roti and Indian Breads',
    portion_description: '1 roti (50g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 258,
    protein: 9.2,
    carbs: 52.4,
    fat: 1.4,
    fiber: 8.2,
  },
  {
    name: 'Plain Naan (Tandoori White Flour Bread)',
    category: 'Roti and Indian Breads',
    portion_description: '1 naan (90g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 292,
    protein: 8.2,
    carbs: 52.6,
    fat: 5.2,
    fiber: 2.4,
  },
  {
    name: 'Butter Naan',
    category: 'Roti and Indian Breads',
    portion_description: '1 butter naan (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 335,
    protein: 8.0,
    carbs: 50.8,
    fat: 10.4,
    fiber: 2.2,
  },
  {
    name: 'Garlic Naan',
    category: 'Roti and Indian Breads',
    portion_description: '1 garlic butter naan (105g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 328,
    protein: 8.1,
    carbs: 51.2,
    fat: 9.6,
    fiber: 2.5,
  },
  {
    name: 'Rumali Roti',
    category: 'Roti and Indian Breads',
    portion_description: '1 large handkerchief bread (70g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 284,
    protein: 7.9,
    carbs: 54.2,
    fat: 3.8,
    fiber: 2.1,
  },
  {
    name: 'Poori / Puri (Deep Fried Whole Wheat Bread)',
    category: 'Roti and Indian Breads',
    portion_description: '2 puris (60g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 382,
    protein: 7.4,
    carbs: 45.8,
    fat: 18.6,
    fiber: 5.2,
  },
  {
    name: 'Bhatura (Deep Fried Leavened Bread)',
    category: 'Roti and Indian Breads',
    portion_description: '1 large bhatura (90g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 368,
    protein: 7.2,
    carbs: 46.2,
    fat: 17.1,
    fiber: 2.2,
  },
  {
    name: 'Malabar Parotta (Kerala Flaky Bread)',
    category: 'Roti and Indian Breads',
    portion_description: '1 parotta (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 348,
    protein: 6.8,
    carbs: 48.2,
    fat: 14.2,
    fiber: 1.8,
  },
  {
    name: 'Missi Roti (Gram Flour & Spices)',
    category: 'Roti and Indian Breads',
    portion_description: '1 medium roti (55g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 282,
    protein: 10.4,
    carbs: 46.2,
    fat: 5.8,
    fiber: 7.4,
  },
  {
    name: 'Egg Kothu Parotta (Shredded Parotta with Eggs & Salna)',
    category: 'Roti and Indian Breads',
    portion_description: '1 plate (250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 228,
    protein: 8.6,
    carbs: 28.4,
    fat: 9.2,
    fiber: 2.4,
  },
  {
    name: 'Chicken Kothu Parotta (Shredded Parotta with Chicken)',
    category: 'Roti and Indian Breads',
    portion_description: '1 plate (260g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 242,
    protein: 11.4,
    carbs: 26.8,
    fat: 10.2,
    fiber: 2.2,
  },

  // RICE DISHES & BIRYANI
  {
    name: 'Steamed White Basmati Rice (Cooked)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.6,
  },
  {
    name: 'Steamed Brown Basmati Rice (Cooked)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 122,
    protein: 2.8,
    carbs: 25.6,
    fat: 0.9,
    fiber: 1.8,
  },
  {
    name: 'Jeera Rice (Cumin Spiced Rice)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 156,
    protein: 2.8,
    carbs: 28.4,
    fat: 3.2,
    fiber: 0.8,
  },
  {
    name: 'Vegetable Biryani (Hyderabadi / Dum Style)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 plate / serving (250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 168,
    protein: 3.8,
    carbs: 26.4,
    fat: 5.1,
    fiber: 2.6,
  },
  {
    name: 'Chicken Dum Biryani',
    category: 'Rice and Grain Dishes',
    portion_description: '1 plate with chicken (300g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 198,
    protein: 9.8,
    carbs: 24.2,
    fat: 6.9,
    fiber: 1.4,
  },
  {
    name: 'Mutton Dum Biryani',
    category: 'Rice and Grain Dishes',
    portion_description: '1 plate with mutton (300g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 224,
    protein: 10.6,
    carbs: 23.8,
    fat: 9.4,
    fiber: 1.3,
  },
  {
    name: 'Egg Biryani (Boiled Eggs with Spiced Rice)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 plate with 2 eggs (280g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 182,
    protein: 7.2,
    carbs: 25.1,
    fat: 5.8,
    fiber: 1.2,
  },
  {
    name: 'Prawn Biryani',
    category: 'Rice and Grain Dishes',
    portion_description: '1 plate (280g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 186,
    protein: 9.2,
    carbs: 24.6,
    fat: 5.4,
    fiber: 1.2,
  },
  {
    name: 'Curd Rice (Thayir Sadam with Mustard Tempering)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 142,
    protein: 3.8,
    carbs: 22.4,
    fat: 4.1,
    fiber: 0.8,
  },
  {
    name: 'Lemon Rice (Chitranna with Peanuts)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 164,
    protein: 3.2,
    carbs: 27.6,
    fat: 4.4,
    fiber: 1.4,
  },
  {
    name: 'Tamarind Rice (Puliyodharai)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 176,
    protein: 3.4,
    carbs: 29.8,
    fat: 4.9,
    fiber: 1.8,
  },
  {
    name: 'Tomato Rice (Thakkali Sadam)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 152,
    protein: 3.0,
    carbs: 26.2,
    fat: 3.8,
    fiber: 1.6,
  },
  {
    name: 'Bisi Bele Bath (Spiced Lentil Rice with Vegetables)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 medium bowl (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 158,
    protein: 4.6,
    carbs: 25.4,
    fat: 4.2,
    fiber: 2.8,
  },
  {
    name: 'Moong Dal Khichdi (Comfort Rice & Yellow Lentils)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 138,
    protein: 4.8,
    carbs: 23.6,
    fat: 2.8,
    fiber: 2.4,
  },
  {
    name: 'Vegetable Pulao (Pilaf with Green Peas & Carrots)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 148,
    protein: 3.4,
    carbs: 26.8,
    fat: 3.1,
    fiber: 2.2,
  },
  {
    name: 'Ghee Rice (Neychoru)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 182,
    protein: 2.8,
    carbs: 27.4,
    fat: 6.8,
    fiber: 0.6,
  },
  {
    name: 'Sambar Rice (South Indian Sambar Sadam)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 bowl (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 136,
    protein: 3.8,
    carbs: 24.2,
    fat: 2.6,
    fiber: 2.4,
  },

  // DAL, LENTILS, SAMBAR & RASAM
  {
    name: 'Dal Tadka (Yellow Toor Dal Tempered with Garlic & Ghee)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium katori / bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 116,
    protein: 5.8,
    carbs: 14.2,
    fat: 3.8,
    fiber: 3.4,
  },
  {
    name: 'Dal Fry (Cooked Toor/Moong with Onion Tomato Masala)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 124,
    protein: 5.6,
    carbs: 14.8,
    fat: 4.6,
    fiber: 3.2,
  },
  {
    name: 'Dal Makhani (Black Lentils & Kidney Beans with Butter)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 168,
    protein: 6.2,
    carbs: 16.4,
    fat: 8.6,
    fiber: 4.8,
  },
  {
    name: 'Chana Masala / Punjabi Chole (Spiced Chickpeas)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 154,
    protein: 7.2,
    carbs: 21.8,
    fat: 4.2,
    fiber: 6.1,
  },
  {
    name: 'Rajma Masala (Red Kidney Beans Curry)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 142,
    protein: 6.8,
    carbs: 20.4,
    fat: 3.8,
    fiber: 5.8,
  },
  {
    name: 'Moong Dal (Simple Boiled Yellow Moong)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 98,
    protein: 6.4,
    carbs: 14.6,
    fat: 1.4,
    fiber: 3.6,
  },
  {
    name: 'Masoor Dal (Red Lentil Curry)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 108,
    protein: 6.2,
    carbs: 15.2,
    fat: 2.2,
    fiber: 3.8,
  },
  {
    name: 'Chana Dal Tadka (Bengal Gram Curry)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 132,
    protein: 6.9,
    carbs: 17.8,
    fat: 3.6,
    fiber: 4.9,
  },
  {
    name: 'Kala Chana Curry (Brown Chickpea Gravy)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 146,
    protein: 7.4,
    carbs: 21.2,
    fat: 3.4,
    fiber: 6.4,
  },
  {
    name: 'Palak Dal / Dal Palak (Lentils Cooked with Fresh Spinach)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 104,
    protein: 5.9,
    carbs: 13.4,
    fat: 3.1,
    fiber: 4.2,
  },
  {
    name: 'Panchmel Dal (Five Lentil Rajasthani Dal)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 136,
    protein: 7.1,
    carbs: 16.8,
    fat: 4.2,
    fiber: 4.2,
  },
  {
    name: 'Traditional South Indian Sambar (Vegetables & Toor Dal)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 78,
    protein: 3.4,
    carbs: 11.6,
    fat: 1.8,
    fiber: 2.8,
  },
  {
    name: 'Tomato Rasam',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 cup / small bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 42,
    protein: 1.2,
    carbs: 6.8,
    fat: 1.1,
    fiber: 1.0,
  },
  {
    name: 'Pepper Rasam (Milagu Rasam)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 cup (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 38,
    protein: 1.1,
    carbs: 5.9,
    fat: 0.9,
    fiber: 0.8,
  },
  {
    name: 'Mor Kuzhambu / Buttermilk Curry (South Indian Kadhi)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 86,
    protein: 3.2,
    carbs: 7.4,
    fat: 4.8,
    fiber: 1.4,
  },
  {
    name: 'Punjabi Kadhi Pakora (Yogurt & Gram Flour Curry with Fritters)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 134,
    protein: 4.8,
    carbs: 13.2,
    fat: 6.8,
    fiber: 2.4,
  },

  // VEGETARIAN CURRIES, PANEER & TOFU
  {
    name: 'Paneer Butter Masala',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 218,
    protein: 8.4,
    carbs: 7.8,
    fat: 17.2,
    fiber: 1.6,
  },
  {
    name: 'Palak Paneer (Spinach & Cottage Cheese)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 164,
    protein: 9.2,
    carbs: 5.4,
    fat: 11.8,
    fiber: 3.2,
  },
  {
    name: 'Kadai Paneer (Capsicum & Roasted Spices)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 196,
    protein: 8.8,
    carbs: 6.8,
    fat: 14.8,
    fiber: 2.4,
  },
  {
    name: 'Matar Paneer (Green Peas & Cottage Cheese)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 178,
    protein: 8.6,
    carbs: 9.4,
    fat: 11.6,
    fiber: 2.8,
  },
  {
    name: 'Shahi Paneer (Cashew Cream Gravy)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 236,
    protein: 8.2,
    carbs: 9.2,
    fat: 18.6,
    fiber: 1.4,
  },
  {
    name: 'Paneer Bhurji (Scrambled Paneer with Onions & Spices)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 medium bowl (140g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 224,
    protein: 13.8,
    carbs: 5.2,
    fat: 16.4,
    fiber: 1.8,
  },
  {
    name: 'Paneer Tikka (Grilled & Marinated Skewers)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '4 pieces (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 212,
    protein: 14.2,
    carbs: 6.4,
    fat: 14.2,
    fiber: 1.6,
  },
  {
    name: 'Malai Kofta (Paneer Dumplings in Cream Gravy)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '2 koftas with gravy (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 248,
    protein: 5.8,
    carbs: 14.6,
    fat: 18.4,
    fiber: 2.2,
  },
  {
    name: 'Tofu Bhurji (Scrambled Tofu with Spices & Tomatoes)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 medium bowl (140g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 118,
    protein: 11.2,
    carbs: 3.8,
    fat: 6.8,
    fiber: 1.8,
  },
  {
    name: 'Tofu Matar Masala (Tofu & Green Peas Curry)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 124,
    protein: 9.4,
    carbs: 7.8,
    fat: 6.2,
    fiber: 2.6,
  },
  {
    name: 'Tofu Tikka (Marinated & Grilled Tofu Skewers)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '4 pieces (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 136,
    protein: 12.8,
    carbs: 4.2,
    fat: 7.6,
    fiber: 2.1,
  },
  {
    name: 'Soya Chunks Curry (Meal Maker Gravy)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 148,
    protein: 16.4,
    carbs: 10.2,
    fat: 4.2,
    fiber: 5.6,
  },
  {
    name: 'Mushroom Masala (Indian Spiced Mushrooms in Onion Gravy)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 92,
    protein: 3.8,
    carbs: 7.2,
    fat: 5.6,
    fiber: 2.4,
  },

  // VEGETABLES & SABZIS
  {
    name: 'Aloo Gobi (Potato & Cauliflower Dry Sabzi)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 112,
    protein: 2.8,
    carbs: 15.6,
    fat: 4.4,
    fiber: 3.2,
  },
  {
    name: 'Aloo Jeera (Dry Cumin Spiced Potatoes)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (140g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 126,
    protein: 2.2,
    carbs: 18.4,
    fat: 5.1,
    fiber: 2.8,
  },
  {
    name: 'Bhindi Masala (Spiced Okra / Ladyfinger)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (140g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 104,
    protein: 2.6,
    carbs: 10.8,
    fat: 5.6,
    fiber: 4.2,
  },
  {
    name: 'Baingan Bharta (Roasted Eggplant Mash)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 96,
    protein: 2.1,
    carbs: 9.8,
    fat: 5.4,
    fiber: 4.6,
  },
  {
    name: 'Aloo Methi (Potatoes with Fresh Fenugreek Leaves)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 118,
    protein: 3.2,
    carbs: 16.2,
    fat: 4.6,
    fiber: 3.8,
  },
  {
    name: 'Sarson Ka Saag (Mustard Greens & Spinach Puree)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 92,
    protein: 3.8,
    carbs: 7.4,
    fat: 5.2,
    fiber: 4.8,
  },
  {
    name: 'Mixed Vegetable Curry / Veg Korma',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 126,
    protein: 3.4,
    carbs: 13.8,
    fat: 6.4,
    fiber: 3.6,
  },
  {
    name: 'Avial (Kerala Mixed Vegetables with Coconut & Yogurt)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 118,
    protein: 2.8,
    carbs: 11.4,
    fat: 6.8,
    fiber: 3.8,
  },
  {
    name: 'Cabbage Thoran (Shredded Cabbage with Coconut)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 84,
    protein: 2.2,
    carbs: 7.8,
    fat: 4.9,
    fiber: 3.1,
  },
  {
    name: 'Beans Poriyal (Green Beans Stir Fry with Coconut)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 78,
    protein: 2.6,
    carbs: 8.2,
    fat: 3.8,
    fiber: 3.4,
  },
  {
    name: 'Lauki Ki Sabzi (Bottle Gourd Curry)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 62,
    protein: 1.4,
    carbs: 6.8,
    fat: 3.2,
    fiber: 2.2,
  },
  {
    name: 'Karela Masala / Bitter Gourd Fry',
    category: 'Vegetables and Sabzi',
    portion_description: '1 small bowl (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 94,
    protein: 2.6,
    carbs: 9.8,
    fat: 5.2,
    fiber: 4.1,
  },
  {
    name: 'Vegetable Kootu (South Indian Veggies & Chana Dal with Coconut)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 108,
    protein: 4.2,
    carbs: 13.8,
    fat: 4.1,
    fiber: 3.8,
  },

  // CHICKEN, MUTTON, FISH & EGGS
  {
    name: 'Butter Chicken / Murgh Makhani',
    category: 'Chicken and Poultry',
    portion_description: '1 serving with chicken pieces (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 228,
    protein: 15.4,
    carbs: 6.2,
    fat: 15.8,
    fiber: 1.2,
  },
  {
    name: 'Chicken Tikka Masala',
    category: 'Chicken and Poultry',
    portion_description: '1 serving (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 196,
    protein: 16.8,
    carbs: 5.8,
    fat: 11.6,
    fiber: 1.4,
  },
  {
    name: 'Homestyle Chicken Curry (Tariwala Chicken)',
    category: 'Chicken and Poultry',
    portion_description: '1 medium bowl (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 164,
    protein: 18.2,
    carbs: 3.8,
    fat: 8.4,
    fiber: 1.1,
  },
  {
    name: 'Chicken Chettinad (Spiced Pepper & Coconut Gravy)',
    category: 'Chicken and Poultry',
    portion_description: '1 serving (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 182,
    protein: 17.6,
    carbs: 4.6,
    fat: 10.4,
    fiber: 1.6,
  },
  {
    name: 'Tandoori Chicken (Skinless Marinated Bone-in Leg)',
    category: 'Chicken and Poultry',
    portion_description: '1 whole leg / piece (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 184,
    protein: 24.6,
    carbs: 3.2,
    fat: 7.8,
    fiber: 0.6,
  },
  {
    name: 'Chicken Tikka (Boneless Grilled Skewers)',
    category: 'Chicken and Poultry',
    portion_description: '5 pieces (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 172,
    protein: 26.2,
    carbs: 2.8,
    fat: 5.9,
    fiber: 0.5,
  },
  {
    name: 'Chicken 65 (Spiced Crisp Chicken Bites)',
    category: 'Chicken and Poultry',
    portion_description: '1 portion (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 246,
    protein: 21.4,
    carbs: 8.6,
    fat: 13.8,
    fiber: 0.8,
  },
  {
    name: 'Chicken Sukka (Mangalorean Dry Coconut Chicken)',
    category: 'Chicken and Poultry',
    portion_description: '1 bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 214,
    protein: 20.8,
    carbs: 4.8,
    fat: 12.4,
    fiber: 2.1,
  },
  {
    name: 'Chicken Korma (Rich Cashew & Yogurt Gravy)',
    category: 'Chicken and Poultry',
    portion_description: '1 serving (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 208,
    protein: 16.2,
    carbs: 5.2,
    fat: 13.6,
    fiber: 1.2,
  },
  {
    name: 'Mutton Rogan Josh (Kashmiri Lamb Curry)',
    category: 'Mutton and Meat',
    portion_description: '1 serving (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 218,
    protein: 17.4,
    carbs: 4.2,
    fat: 14.6,
    fiber: 1.2,
  },
  {
    name: 'Homestyle Mutton Curry / Goat Meat Gravy',
    category: 'Mutton and Meat',
    portion_description: '1 serving (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 198,
    protein: 18.2,
    carbs: 3.6,
    fat: 12.2,
    fiber: 1.0,
  },
  {
    name: 'Keema Matar (Minced Mutton with Green Peas)',
    category: 'Mutton and Meat',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 212,
    protein: 16.8,
    carbs: 6.2,
    fat: 13.4,
    fiber: 2.0,
  },
  {
    name: 'South Indian Fish Curry (Meen Kuzhambu in Tamarind Gravy)',
    category: 'Fish and Seafood',
    portion_description: '1 serving with 1 fish steak (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 138,
    protein: 16.2,
    carbs: 4.4,
    fat: 6.2,
    fiber: 1.2,
  },
  {
    name: 'Goan Fish Curry (Coconut & Kokum Fish Gravy)',
    category: 'Fish and Seafood',
    portion_description: '1 serving (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 154,
    protein: 15.8,
    carbs: 4.8,
    fat: 8.1,
    fiber: 1.4,
  },
  {
    name: 'Bengali Fish Curry (Macher Jhol with Mustard)',
    category: 'Fish and Seafood',
    portion_description: '1 serving (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 128,
    protein: 16.4,
    carbs: 3.8,
    fat: 5.2,
    fiber: 1.0,
  },
  {
    name: 'Indian Fried Fish / Rava Fish Fry (Kingfish / Surmai)',
    category: 'Fish and Seafood',
    portion_description: '1 steak slice (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 218,
    protein: 21.8,
    carbs: 6.4,
    fat: 11.6,
    fiber: 0.6,
  },
  {
    name: 'Prawn Masala (Shrimp in Spicy Onion Tomato Gravy)',
    category: 'Fish and Seafood',
    portion_description: '1 medium bowl (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 142,
    protein: 17.6,
    carbs: 5.4,
    fat: 5.6,
    fiber: 1.2,
  },
  {
    name: 'Indian Egg Curry (Boiled Eggs in Spiced Gravy)',
    category: 'Egg Dishes',
    portion_description: '1 serving with 2 eggs (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 152,
    protein: 9.8,
    carbs: 4.6,
    fat: 10.2,
    fiber: 1.0,
  },
  {
    name: 'Egg Bhurji (Indian Spiced Scrambled Eggs with Onion & Tomato)',
    category: 'Egg Dishes',
    portion_description: '1 serving with 2 eggs (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 182,
    protein: 12.4,
    carbs: 3.6,
    fat: 12.8,
    fiber: 0.8,
  },

  // SNACKS, CHAAT, CHUTNEYS & STREET FOOD
  {
    name: 'Samosa (Potato & Pea Stuffed Fried Pastry)',
    category: 'Snacks and Chaat',
    portion_description: '1 piece (75g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 308,
    protein: 5.2,
    carbs: 36.4,
    fat: 15.8,
    fiber: 3.4,
  },
  {
    name: 'Onion Pakora / Kanda Bhaji',
    category: 'Snacks and Chaat',
    portion_description: '4-5 fritters (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 286,
    protein: 6.4,
    carbs: 28.2,
    fat: 16.4,
    fiber: 4.2,
  },
  {
    name: 'Kachori (Spiced Moong Dal / Pyaaz Fried Pastry)',
    category: 'Snacks and Chaat',
    portion_description: '1 kachori (75g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 342,
    protein: 6.8,
    carbs: 42.6,
    fat: 16.4,
    fiber: 3.8,
  },
  {
    name: 'Pani Puri / Golgappa (Puffed Crisps with Mint Water)',
    category: 'Snacks and Chaat',
    portion_description: '6 filled puris (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 148,
    protein: 3.2,
    carbs: 26.4,
    fat: 3.4,
    fiber: 2.6,
  },
  {
    name: 'Bhel Puri (Puffed Rice, Chutneys, Sev)',
    category: 'Snacks and Chaat',
    portion_description: '1 plate (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 218,
    protein: 5.1,
    carbs: 38.6,
    fat: 5.2,
    fiber: 3.8,
  },
  {
    name: 'Sev Puri',
    category: 'Snacks and Chaat',
    portion_description: '1 plate of 6 pieces (140g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 264,
    protein: 5.4,
    carbs: 36.8,
    fat: 10.6,
    fiber: 3.6,
  },
  {
    name: 'Dahi Vada / Dahi Bhalla (Lentil Fritters in Yogurt)',
    category: 'Snacks and Chaat',
    portion_description: '2 vadas with yogurt (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 178,
    protein: 6.4,
    carbs: 22.8,
    fat: 6.9,
    fiber: 2.2,
  },
  {
    name: 'Dahi Puri (Crisp Puris with Potato, Yogurt & Chutneys)',
    category: 'Snacks and Chaat',
    portion_description: '1 plate of 6 pieces (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 186,
    protein: 4.2,
    carbs: 27.4,
    fat: 6.8,
    fiber: 2.4,
  },
  {
    name: 'Pav Bhaji (Spiced Mashed Vegetable Curry with Buttered Pav)',
    category: 'Snacks and Chaat',
    portion_description: '1 plate with 2 pavs (300g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 188,
    protein: 4.6,
    carbs: 26.8,
    fat: 7.1,
    fiber: 3.6,
  },
  {
    name: 'Vada Pav (Mumbai Potato Fritter in Bun)',
    category: 'Snacks and Chaat',
    portion_description: '1 vada pav (130g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 285,
    protein: 6.2,
    carbs: 42.4,
    fat: 10.2,
    fiber: 3.4,
  },
  {
    name: 'Aloo Tikki (Crispy Potato Cutlet)',
    category: 'Snacks and Chaat',
    portion_description: '2 pieces (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 214,
    protein: 3.8,
    carbs: 31.6,
    fat: 8.2,
    fiber: 3.2,
  },
  {
    name: 'Roasted Makhana / Fox Nuts (Lightly Spiced in Ghee)',
    category: 'Snacks and Chaat',
    portion_description: '1 bowl (30g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 384,
    protein: 9.8,
    carbs: 68.2,
    fat: 8.4,
    fiber: 14.2,
  },
  {
    name: 'Roasted Chana / Bhuna Chana (Dry Roasted Chickpeas)',
    category: 'Snacks and Chaat',
    portion_description: '1 handful / small bowl (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 368,
    protein: 19.8,
    carbs: 56.4,
    fat: 5.6,
    fiber: 16.8,
  },
  {
    name: 'Murukku / Chakli (Crisp Spiral Snack)',
    category: 'Snacks and Chaat',
    portion_description: '3 pieces (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 492,
    protein: 7.2,
    carbs: 58.4,
    fat: 25.6,
    fiber: 3.8,
  },
  {
    name: 'Chana Sundal (Tempered Chickpeas with Coconut)',
    category: 'Snacks and Chaat',
    portion_description: '1 medium bowl (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 162,
    protein: 7.8,
    carbs: 23.4,
    fat: 4.6,
    fiber: 6.2,
  },
  {
    name: 'Fresh Coconut Chutney (South Indian Style)',
    category: 'Snacks and Chaat',
    portion_description: '2 tablespoons (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 212,
    protein: 3.2,
    carbs: 7.4,
    fat: 19.6,
    fiber: 4.8,
  },
  {
    name: 'Green Mint Coriander Chutney (Hari Chutney)',
    category: 'Snacks and Chaat',
    portion_description: '2 tablespoons (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 48,
    protein: 2.4,
    carbs: 6.8,
    fat: 1.2,
    fiber: 3.6,
  },
  {
    name: 'Tomato Onion Chutney (Kara Chutney)',
    category: 'Snacks and Chaat',
    portion_description: '2 tablespoons (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 76,
    protein: 1.8,
    carbs: 8.4,
    fat: 4.2,
    fiber: 2.1,
  },
  {
    name: 'Tamarind Date Sweet Chutney (Saunth)',
    category: 'Snacks and Chaat',
    portion_description: '2 tablespoons (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 198,
    protein: 1.2,
    carbs: 48.2,
    fat: 0.4,
    fiber: 2.8,
  },
  {
    name: 'Indian Mango Pickle / Aam Ka Achaar (in Mustard Oil)',
    category: 'Snacks and Chaat',
    portion_description: '1 tablespoon (15g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 168,
    protein: 1.4,
    carbs: 9.2,
    fat: 14.6,
    fiber: 2.8,
  },

  // DAIRY & BEVERAGES
  {
    name: 'Fresh Cow Milk Curd / Dahi (Plain Homemade Yogurt)',
    category: 'Dairy and Beverages',
    portion_description: '1 medium katori / bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.1,
    fiber: 0,
  },
  {
    name: 'Fresh Paneer (Indian Cottage Cheese, Raw)',
    category: 'Dairy and Beverages',
    portion_description: '1 block (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 265,
    protein: 18.3,
    carbs: 3.4,
    fat: 20.8,
    fiber: 0,
  },
  {
    name: 'Low Fat Paneer',
    category: 'Dairy and Beverages',
    portion_description: '1 block (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 168,
    protein: 24.2,
    carbs: 4.8,
    fat: 5.8,
    fiber: 0,
  },
  {
    name: 'Pure Desi Ghee (Clarified Butter)',
    category: 'Dairy and Beverages',
    portion_description: '1 tablespoon (14g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 884,
    protein: 0.1,
    carbs: 0,
    fat: 99.5,
    fiber: 0,
  },
  {
    name: 'Cow Milk (Toned 3% Fat, Boiled)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (200ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 58,
    protein: 3.2,
    carbs: 4.7,
    fat: 3.0,
    fiber: 0,
  },
  {
    name: 'Buffalo Milk (Full Cream, Boiled)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (200ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 97,
    protein: 3.8,
    carbs: 5.2,
    fat: 6.9,
    fiber: 0,
  },
  {
    name: 'Chaas / Spiced Buttermilk (Salt, Cumin & Ginger)',
    category: 'Dairy and Beverages',
    portion_description: '1 large glass (250ml / 250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 28,
    protein: 1.8,
    carbs: 2.6,
    fat: 1.1,
    fiber: 0.1,
  },
  {
    name: 'Sweet Lassi (Traditional Yogurt Drink)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (250ml / 260g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 92,
    protein: 2.8,
    carbs: 14.6,
    fat: 2.4,
    fiber: 0,
  },
  {
    name: 'Mango Lassi (Yogurt & Mango Pulp)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (250ml / 260g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 108,
    protein: 2.6,
    carbs: 18.2,
    fat: 2.6,
    fiber: 0.6,
  },
  {
    name: 'Rose Milk / Rooh Afza Milk (Chilled Flavored Milk)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (250ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 84,
    protein: 2.8,
    carbs: 13.6,
    fat: 2.2,
    fiber: 0,
  },
  {
    name: 'Indian Masala Chai (with Milk & Sugar)',
    category: 'Dairy and Beverages',
    portion_description: '1 teacup (150ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 68,
    protein: 2.2,
    carbs: 9.8,
    fat: 2.1,
    fiber: 0,
  },
  {
    name: 'Indian Masala Chai (with Milk, No Sugar)',
    category: 'Dairy and Beverages',
    portion_description: '1 teacup (150ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 38,
    protein: 2.2,
    carbs: 2.9,
    fat: 2.1,
    fiber: 0,
  },
  {
    name: 'Adrak Chai / Ginger Tea (with Milk & Light Sugar)',
    category: 'Dairy and Beverages',
    portion_description: '1 teacup (150ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 62,
    protein: 2.1,
    carbs: 8.6,
    fat: 2.0,
    fiber: 0,
  },
  {
    name: 'South Indian Filter Coffee (with Milk & Sugar)',
    category: 'Dairy and Beverages',
    portion_description: '1 dabara / cup (150ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 74,
    protein: 2.4,
    carbs: 10.6,
    fat: 2.4,
    fiber: 0,
  },
  {
    name: 'South Indian Filter Coffee (Strong Decoction, No Sugar)',
    category: 'Dairy and Beverages',
    portion_description: '1 dabara / cup (150ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 38,
    protein: 2.2,
    carbs: 3.0,
    fat: 2.1,
    fiber: 0,
  },
  {
    name: 'Tender Coconut Water (Fresh Elaneer)',
    category: 'Dairy and Beverages',
    portion_description: '1 full coconut water (250ml / 250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 19,
    protein: 0.7,
    carbs: 3.7,
    fat: 0.2,
    fiber: 1.1,
  },
  {
    name: 'Fresh Nimbu Pani / Shikanji (Sweet & Salt Lime Water)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (250ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 36,
    protein: 0.2,
    carbs: 8.8,
    fat: 0.1,
    fiber: 0.2,
  },
  {
    name: 'Jaljeera (Spiced Cumin & Mint Cooler)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (250ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 24,
    protein: 0.4,
    carbs: 5.2,
    fat: 0.2,
    fiber: 0.6,
  },
  {
    name: 'Badam Milk (Almond, Saffron & Cardamom Milk)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (200ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 96,
    protein: 3.6,
    carbs: 12.4,
    fat: 3.8,
    fiber: 0.8,
  },
  {
    name: 'Aam Panna (Raw Mango Summer Drink)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (250ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 54,
    protein: 0.4,
    carbs: 13.2,
    fat: 0.1,
    fiber: 0.6,
  },
  {
    name: 'Sattu Drink (Roasted Gram Flour with Cumin & Lemon)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (250ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 78,
    protein: 4.8,
    carbs: 11.6,
    fat: 1.4,
    fiber: 3.4,
  },

  // SWEETS & DESSERTS (MITHAI)
  {
    name: 'Gulab Jamun (Fried Milk Solids in Rose Sugar Syrup)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2 pieces (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 326,
    protein: 5.4,
    carbs: 54.2,
    fat: 10.4,
    fiber: 0.8,
  },
  {
    name: 'Rasgulla (Spongy Chhena Cottage Cheese in Light Syrup)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2 pieces (90g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 186,
    protein: 4.8,
    carbs: 36.4,
    fat: 2.4,
    fiber: 0.2,
  },
  {
    name: 'Rasmalai (Soft Cheese Patties in Cardamom Saffron Milk)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2 pieces with milk (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 218,
    protein: 6.8,
    carbs: 27.6,
    fat: 9.4,
    fiber: 0.4,
  },
  {
    name: 'Kaju Katli (Cashew Nut Fudge)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2 diamond pieces (35g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 442,
    protein: 9.8,
    carbs: 56.4,
    fat: 20.2,
    fiber: 2.1,
  },
  {
    name: 'Kaju Pista Roll (Cashew & Pistachio Sweet Roll)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2 pieces (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 462,
    protein: 10.4,
    carbs: 52.8,
    fat: 23.6,
    fiber: 2.6,
  },
  {
    name: 'Gajar Ka Halwa (Carrot Pudding with Ghee & Milk)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 medium bowl (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 234,
    protein: 4.2,
    carbs: 31.8,
    fat: 10.4,
    fiber: 2.4,
  },
  {
    name: 'Sooji Halwa / Kesari (Semolina with Saffron & Ghee)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 small bowl (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 298,
    protein: 3.8,
    carbs: 46.2,
    fat: 11.2,
    fiber: 1.2,
  },
  {
    name: 'Moong Dal Halwa',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 small bowl (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 364,
    protein: 8.2,
    carbs: 44.8,
    fat: 17.6,
    fiber: 3.2,
  },
  {
    name: 'Rice Kheer / Payasam (Indian Rice Pudding with Cardamom)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 148,
    protein: 4.2,
    carbs: 22.8,
    fat: 4.8,
    fiber: 0.5,
  },
  {
    name: 'Semiya Payasam (Vermicelli Kheer)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 162,
    protein: 4.4,
    carbs: 24.6,
    fat: 5.2,
    fiber: 0.6,
  },
  {
    name: 'Besan Ladoo (Roasted Gram Flour & Ghee Sweet)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 medium ladoo (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 468,
    protein: 8.4,
    carbs: 54.2,
    fat: 24.6,
    fiber: 4.2,
  },
  {
    name: 'Motichoor Ladoo',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 medium ladoo (45g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 422,
    protein: 4.6,
    carbs: 62.4,
    fat: 17.8,
    fiber: 1.8,
  },
  {
    name: 'Mysore Pak (Ghee, Gram Flour & Sugar Sweet)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 square (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 512,
    protein: 6.2,
    carbs: 52.8,
    fat: 31.4,
    fiber: 2.4,
  },
  {
    name: 'Jalebi (Crisp Swirls in Saffron Sugar Syrup)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2-3 jalebis (75g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 388,
    protein: 2.8,
    carbs: 72.4,
    fat: 9.8,
    fiber: 0.6,
  },
  {
    name: 'Shrikhand (Cardamom & Saffron Strained Yogurt Sweet)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 small bowl (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 254,
    protein: 7.6,
    carbs: 34.2,
    fat: 9.8,
    fiber: 0.2,
  },
  {
    name: 'Doodh Peda (Milk Mawa & Cardamom Sweet)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2 pieces (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 388,
    protein: 9.6,
    carbs: 54.2,
    fat: 15.4,
    fiber: 0.4,
  },
  {
    name: 'Modak / Kozhukattai (Steamed Rice Dumpling with Sweet Coconut Jaggery)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2 modaks (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 218,
    protein: 3.1,
    carbs: 44.2,
    fat: 3.6,
    fiber: 1.8,
  },
  {
    name: 'Sandesh (Bengali Fresh Chhena Sweet)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2 pieces (50g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 268,
    protein: 11.2,
    carbs: 36.4,
    fat: 8.6,
    fiber: 0.2,
  },
];

async function seedAllIndianFoods() {
  console.log('====================================================');
  console.log('VITALIS: SEEDING ANUVAAD / IFCT INDIAN FOOD CATALOG');
  console.log('====================================================\n');

  const ifctFoods = getIFCTFoods();
  console.log(`Loaded ${ifctFoods.length} raw foods from IFCT 2017.`);
  console.log(`Loaded ${anuvaadCookedFoods.length} cooked recipes from Anuvaad INDB.\n`);

  const merged = [...anuvaadCookedFoods, ...ifctFoods];
  console.log(`Total candidate Indian food records: ${merged.length}`);

  // Fetch existing foods from Supabase for deduplication
  let allExisting = [];
  let from = 0;
  const pageSize = 1000;
  while (true) {
    const { data: batch, error: fetchErr } = await supabase
      .from('foods')
      .select('name')
      .range(from, from + pageSize - 1);

    if (fetchErr) {
      console.error('❌ Error fetching existing foods:', fetchErr);
      return;
    }
    allExisting = allExisting.concat(batch || []);
    if (!batch || batch.length < pageSize) break;
    from += pageSize;
  }

  const existingNames = new Set((allExisting || []).map(r => r.name.toLowerCase().trim()));
  console.log(`Found ${existingNames.size} existing foods in database.`);

  const toInsert = [];
  const skipped = [];

  for (const food of merged) {
    const key = food.name.toLowerCase().trim();
    if (existingNames.has(key)) {
      skipped.push(food.name);
    } else {
      toInsert.push({
        name: food.name,
        category: food.category,
        portion_description: food.portion_description,
        base_amount: food.base_amount,
        base_unit: food.base_unit,
        calories: food.calories,
        protein: food.protein,
        carbs: food.carbs,
        fat: food.fat,
        fiber: food.fiber,
        user_id: null,
      });
      existingNames.add(key);
    }
  }

  console.log(`\nReady to insert: ${toInsert.length} unique Indian foods & recipes.`);
  console.log(`Skipped duplicate: ${skipped.length} foods.`);

  // Write SQL migration
  const migrationPath = path.join(__dirname, '../../supabase/migrations/20260907000003_seed_anuvaad_indian_foods.sql');
  let sqlContent = `-- ==============================================================================\n`;
  sqlContent += `-- VITALIS FOOD DATABASE: ANUVAAD INDIAN NUTRIENT DATABANK & IFCT 2017 SEED\n`;
  sqlContent += `-- Total unique Indian foods & recipes: ${toInsert.length}\n`;
  sqlContent += `-- Sources: Anuvaad INDB (anuvaad.org.in) + ICMR-NIN IFCT 2017\n`;
  sqlContent += `-- User ID: NULL (System Food reference catalog)\n`;
  sqlContent += `-- ==============================================================================\n\n`;
  sqlContent += `INSERT INTO public.foods (name, category, portion_description, base_amount, base_unit, calories, protein, carbs, fat, fiber, user_id) VALUES\n`;

  const valueRows = toInsert.map(f => {
    const nameEsc = f.name.replace(/'/g, "''");
    const catEsc = f.category.replace(/'/g, "''");
    const portionEsc = f.portion_description.replace(/'/g, "''");
    return `  ('${nameEsc}', '${catEsc}', '${portionEsc}', ${f.base_amount}, '${f.base_unit}', ${f.calories}, ${f.protein}, ${f.carbs}, ${f.fat}, ${f.fiber}, NULL)`;
  });

  sqlContent += valueRows.join(',\n') + ';\n';

  fs.writeFileSync(migrationPath, sqlContent, 'utf8');
  console.log(`\n✅ Generated migration SQL file: ${migrationPath}`);
}

seedAllIndianFoods();
