/**
 * VITALIS - Global 15 Food-Composition Databases Importer
 * Datasets:
 * 1. TBCA – Brazilian Food Composition Table (USP / FoRC)
 * 2. Japanese Standard Tables of Food Composition (MEXT Japan 8th Edition)
 * 3. MyFCD – Malaysian Food Composition Database (MOH Malaysia)
 * 4. FOODfiles – New Zealand Food Composition Database (Plant & Food Research / MOH NZ)
 * 5. SAFOODS – South African Food Data System (SAMRC)
 * 6. Singapore Food Insights Database (HPB / SFA Singapore)
 * 7. Thai Food Composition Database (INMU Mahidol University)
 * 8. Vietnamese Food Composition Table (NIN Vietnam)
 * 9. China Food Composition Table (NINH / CDC China)
 * 10. Philippine Food Composition Tables (FNRI - DOST)
 * 11. TürKomp – Turkish Food Composition Database (TÜBİTAK MAM)
 * 12. Tunisian Food Composition Database (INNTA)
 * 13. Kenya Food Composition Tables (MOH Kenya / FAO)
 * 14. Uganda Food Composition Table (MAAIF / FAO)
 * 15. FAO/INFOODS Global Food Composition Databases (BioFoodComp, uFiSh, AnFooD)
 * 
 * Strict Requirements:
 * - Exact published nutrition values per 100g base amount
 * - user_id = NULL
 * - Deduplication against existing 8,504 foods in Vitalis
 * - Preserves existing schema and UI
 */

const fs = require('fs');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || 'https://zqraxlkfiqgaecdslkzu.supabase.co';
const SUPABASE_KEY = process.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_UKmol7CuOwTz3OMqvPRocw_8X7c2flJ';
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

// ============================================================================
// 1. TBCA - Brazilian Food Composition Table (USP / FoRC)
// ============================================================================
const tbcaFoods = [
  {
    name: 'Açaí Berry Pulp (Frozen Pure Unsweetened Euterpe oleracea Pulp)',
    category: 'Fruits and Fruit Juices',
    portion_description: '1 bowl / packet (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 64,
    protein: 1.2,
    carbs: 6.2,
    fat: 3.8,
    fiber: 3.2,
  },
  {
    name: 'Pão de Queijo (Brazilian Cheese Bread Balls Baked with Tapioca Starch & Minas Cheese)',
    category: 'Baked Products',
    portion_description: '3 small balls (60g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 298,
    protein: 6.8,
    carbs: 34.6,
    fat: 14.8,
    fiber: 0.8,
  },
  {
    name: 'Feijoada Completa (Traditional Brazilian Black Bean Stew with Smoked Pork & Sausages)',
    category: 'Meat and Poultry',
    portion_description: '1 large bowl (300g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 168,
    protein: 12.4,
    carbs: 11.8,
    fat: 8.2,
    fiber: 4.6,
  },
  {
    name: 'Farofa de Mandioca (Toasted Seasoned Cassava Flour with Butter & Bacon Bits)',
    category: 'Rice and Grain Dishes',
    portion_description: '2 tablespoons (30g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 412,
    protein: 2.8,
    carbs: 72.4,
    fat: 12.6,
    fiber: 5.4,
  },
  {
    name: 'Tapioca Crepe (Goma de Mandioca Hydrated Cassava Pancake)',
    category: 'Breakfast foods',
    portion_description: '1 crepe (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 242,
    protein: 0.4,
    carbs: 58.6,
    fat: 0.2,
    fiber: 1.2,
  },
  {
    name: 'Moqueca Baiana (Bahian Fish Stew with Coconut Milk, Dende Palm Oil, Bell Peppers & Tomato)',
    category: 'Fish and Seafood',
    portion_description: '1 serving (250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 146,
    protein: 14.2,
    carbs: 4.8,
    fat: 8.2,
    fiber: 1.4,
  },
  {
    name: 'Coxinha de Frango (Brazilian Teardrop Crispy Croquette with Shredded Spiced Chicken)',
    category: 'Snacks and Chaat',
    portion_description: '1 medium coxinha (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 284,
    protein: 11.6,
    carbs: 26.4,
    fat: 14.8,
    fiber: 1.8,
  },
  {
    name: 'Brigadeiro (Traditional Brazilian Chocolate Fudge Truffle with Condensed Milk & Cocoa)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2 pieces (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 382,
    protein: 5.4,
    carbs: 56.8,
    fat: 15.2,
    fiber: 1.6,
  },
  {
    name: 'Picanha (Brazilian Rump Cap Steak with Fat Cap, Grilled on Skewers)',
    category: 'Meat and Poultry',
    portion_description: '1 steak slice (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 278,
    protein: 26.4,
    carbs: 0,
    fat: 18.8,
    fiber: 0,
  },
  {
    name: 'Cupuaçu Fruit Pulp (Theobroma grandiflorum, Frozen Raw Pulp)',
    category: 'Fruits and Fruit Juices',
    portion_description: '1 cup pulp (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 49,
    protein: 0.8,
    carbs: 10.8,
    fat: 0.4,
    fiber: 2.1,
  },
];

// ============================================================================
// 2. JAPANESE STANDARD TABLES OF FOOD COMPOSITION (MEXT Japan 8th Edition)
// ============================================================================
const mextJapanFoods = [
  {
    name: 'Natto (Traditional Fermented Soybeans with Bacillus subtilis var. natto)',
    category: 'Grain Legumes and Pulses',
    portion_description: '1 standard pack (45g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 190,
    protein: 16.5,
    carbs: 12.1,
    fat: 10.0,
    fiber: 6.7,
  },
  {
    name: 'Japanese Silken Tofu / Kinugoshi Tofu',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 block (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 56,
    protein: 5.3,
    carbs: 2.0,
    fat: 3.5,
    fiber: 0.4,
  },
  {
    name: 'Japanese Momen Tofu (Firm Cotton-Pressed Tofu)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 block (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 73,
    protein: 7.0,
    carbs: 1.6,
    fat: 4.9,
    fiber: 0.6,
  },
  {
    name: 'Red Miso Paste / Aka Miso (Fermented Soybean Paste)',
    category: 'Condiments and Spices',
    portion_description: '1 tablespoon (18g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 186,
    protein: 12.8,
    carbs: 19.4,
    fat: 6.0,
    fiber: 5.4,
  },
  {
    name: 'Japanese Udon Noodles (Wheat Flour Noodles, Cooked Boiled)',
    category: 'Cereals and Millets',
    portion_description: '1 bowl cooked (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 99,
    protein: 2.6,
    carbs: 21.6,
    fat: 0.4,
    fiber: 0.8,
  },
  {
    name: 'Japanese Soba Noodles (Buckwheat Noodles, Cooked Boiled)',
    category: 'Cereals and Millets',
    portion_description: '1 bowl cooked (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 132,
    protein: 4.8,
    carbs: 26.4,
    fat: 0.7,
    fiber: 2.0,
  },
  {
    name: 'Shirataki / Konjac Noodles (Glucomannan Yam Noodles, Drained)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 pack drained (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 6,
    protein: 0.2,
    carbs: 2.3,
    fat: 0,
    fiber: 2.2,
  },
  {
    name: 'Wakame Seaweed (Undaria pinnatifida, Dried Raw)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 tablespoon dry (5g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 138,
    protein: 13.0,
    carbs: 41.8,
    fat: 4.0,
    fiber: 35.6,
  },
  {
    name: 'Yaki Nori (Toasted Japanese Seaweed Sheets for Sushi)',
    category: 'Vegetables and Sabzi',
    portion_description: '2 sheets (6g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 188,
    protein: 41.4,
    carbs: 37.2,
    fat: 3.7,
    fiber: 36.0,
  },
  {
    name: 'Shiitake Mushrooms (Lentinula edodes, Fresh Raw)',
    category: 'Vegetables and Sabzi',
    portion_description: '4 medium mushrooms (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 25,
    protein: 2.8,
    carbs: 4.9,
    fat: 0.3,
    fiber: 4.2,
  },
  {
    name: 'Enoki Mushrooms (Flammulina velutipes, Fresh Raw)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 bunch (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 22,
    protein: 2.7,
    carbs: 5.4,
    fat: 0.2,
    fiber: 3.9,
  },
  {
    name: 'Kabocha Squash / Japanese Pumpkin (Cucurbita maxima, Steamed Flesh)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 cup cubes (140g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 83,
    protein: 1.9,
    carbs: 18.5,
    fat: 0.3,
    fiber: 3.5,
  },
  {
    name: 'Unagi Kabayaki (Japanese Freshwater Eel Glazed & Grilled with Sweet Soy)',
    category: 'Fish and Seafood',
    portion_description: '1 fillet (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 293,
    protein: 23.0,
    carbs: 3.1,
    fat: 21.0,
    fiber: 0,
  },
  {
    name: 'Japanese Wagyu Beef (A5 Grade Ribeye, Grilled)',
    category: 'Meat and Poultry',
    portion_description: '1 serving (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 418,
    protein: 15.6,
    carbs: 0,
    fat: 39.8,
    fiber: 0,
  },
  {
    name: 'Matcha Green Tea Powder (Pure Japanese Uji Ceremonial Grade)',
    category: 'Dairy and Beverages',
    portion_description: '1 teaspoon (2g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 324,
    protein: 30.6,
    carbs: 38.5,
    fat: 5.3,
    fiber: 38.5,
  },
  {
    name: 'Takoyaki (Japanese Crispy Battered Octopus Balls with Sauce & Bonito Flakes)',
    category: 'Snacks and Chaat',
    portion_description: '6 balls (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 168,
    protein: 6.4,
    carbs: 21.2,
    fat: 6.8,
    fiber: 1.4,
  },
  {
    name: 'Okonomiyaki (Japanese Savory Cabbage & Pork Pancake with Sauce & Kewpie)',
    category: 'Snacks and Chaat',
    portion_description: '1 pancake (250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 184,
    protein: 7.8,
    carbs: 19.4,
    fat: 8.6,
    fiber: 2.2,
  },
];

// ============================================================================
// 3. MyFCD - Malaysian Food Composition Database (MOH Malaysia)
// ============================================================================
const myFcdFoods = [
  {
    name: 'Nasi Lemak (Fragrant Coconut Rice with Sambal, Fried Anchovies, Egg & Cucumber)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 packet / plate (280g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 188,
    protein: 5.4,
    carbs: 26.8,
    fat: 7.2,
    fiber: 1.8,
  },
  {
    name: 'Roti Canai (Malaysian Flaky Layered Flatbread with Dhal Curry)',
    category: 'Roti and Indian Breads',
    portion_description: '1 piece with dhal (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 312,
    protein: 7.2,
    carbs: 45.4,
    fat: 11.8,
    fiber: 2.8,
  },
  {
    name: 'Beef Rendang (Slow-Cooked Malaysian Spiced Beef in Coconut Milk & Kerisik)',
    category: 'Meat and Poultry',
    portion_description: '1 serving (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 228,
    protein: 19.4,
    carbs: 5.2,
    fat: 14.8,
    fiber: 1.6,
  },
  {
    name: 'Chicken Satay with Peanut Sauce (Grilled Marinated Skewers with Kuah Kacang)',
    category: 'Chicken and Poultry',
    portion_description: '5 skewers with sauce (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 198,
    protein: 16.8,
    carbs: 8.6,
    fat: 11.2,
    fiber: 1.8,
  },
  {
    name: 'Malaysian Curry Laksa (Rice Noodles in Rich Spicy Coconut Curry Broth with Tofu Puffs)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 bowl (350g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 148,
    protein: 5.8,
    carbs: 16.4,
    fat: 6.9,
    fiber: 1.6,
  },
  {
    name: 'Char Kway Teow (Stir-Fried Flat Rice Noodles with Prawns, Cockles, Bean Sprouts & Chives)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 plate (280g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 194,
    protein: 6.8,
    carbs: 24.2,
    fat: 8.2,
    fiber: 1.4,
  },
  {
    name: 'Otak-Otak (Malaysian Spiced Fish Paste with Coconut Milk Steamed in Banana Leaf)',
    category: 'Fish and Seafood',
    portion_description: '2 wrapped pieces (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 154,
    protein: 14.6,
    carbs: 5.8,
    fat: 8.4,
    fiber: 1.1,
  },
  {
    name: 'Pandan Kaya (Malaysian Coconut Egg Jam with Pandan Leaf Extract)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 tablespoon (20g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 278,
    protein: 4.8,
    carbs: 48.6,
    fat: 7.2,
    fiber: 0.6,
  },
  {
    name: 'Teh Tarik (Malaysian Pulled Frothy Black Tea with Sweetened Condensed Milk)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (220ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 78,
    protein: 2.1,
    carbs: 12.4,
    fat: 2.4,
    fiber: 0,
  },
  {
    name: 'Cendol (Shaved Ice with Green Rice Flour Jelly, Gula Melaka Palm Sugar & Coconut Milk)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 bowl (250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 142,
    protein: 1.8,
    carbs: 24.8,
    fat: 4.2,
    fiber: 1.2,
  },
];

// ============================================================================
// 4. FOODfiles - New Zealand Food Composition Database (Plant & Food NZ)
// ============================================================================
const foodFilesNz = [
  {
    name: 'New Zealand Green-Lipped Mussels (Perna canaliculus, Steamed Meat)',
    category: 'Fish and Seafood',
    portion_description: '1 serving (150g meat)',
    base_amount: 100,
    base_unit: 'g',
    calories: 105,
    protein: 18.8,
    carbs: 3.4,
    fat: 1.8,
    fiber: 0,
  },
  {
    name: 'New Zealand Hoki Fillet (Macruronus novaezelandiae, Baked)',
    category: 'Fish and Seafood',
    portion_description: '1 fillet (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 88,
    protein: 19.2,
    carbs: 0,
    fat: 1.2,
    fiber: 0,
  },
  {
    name: 'New Zealand King Salmon / Chinook Salmon (Oncorhynchus tshawytscha, Baked)',
    category: 'Fish and Seafood',
    portion_description: '1 fillet (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 216,
    protein: 22.8,
    carbs: 0,
    fat: 13.9,
    fiber: 0,
  },
  {
    name: 'New Zealand Red Kumara (Sweet Potato, Baked with Skin)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium kumara (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 108,
    protein: 1.6,
    carbs: 24.2,
    fat: 0.3,
    fiber: 3.8,
  },
  {
    name: 'New Zealand Feijoa (Acca sellowiana, Fresh Raw Flesh)',
    category: 'Fruits and Fruit Juices',
    portion_description: '2 feijoas (100g flesh)',
    base_amount: 100,
    base_unit: 'g',
    calories: 55,
    protein: 0.6,
    carbs: 10.8,
    fat: 0.6,
    fiber: 6.4,
  },
  {
    name: 'Zespri SunGold Kiwifruit (Actinidia chinensis, Raw Flesh)',
    category: 'Fruits and Fruit Juices',
    portion_description: '1 kiwifruit (90g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 63,
    protein: 1.0,
    carbs: 14.2,
    fat: 0.3,
    fiber: 1.4,
  },
  {
    name: 'Pure New Zealand Manuka Honey (Raw Monofloral UMF/MGO)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 tablespoon (21g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 328,
    protein: 0.3,
    carbs: 81.4,
    fat: 0,
    fiber: 0.2,
  },
  {
    name: 'New Zealand Farmed Venison Tenderloin (Lean Roasted)',
    category: 'Meat and Poultry',
    portion_description: '1 fillet (130g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 120,
    protein: 25.4,
    carbs: 0,
    fat: 1.9,
    fiber: 0,
  },
];

// ============================================================================
// 5. SAFOODS - South African Food Data System (SAMRC)
// ============================================================================
const saFoods = [
  {
    name: 'Traditional South African Biltong (Air-Cured Spiced Lean Beef Strips with Coriander)',
    category: 'Meat and Poultry',
    portion_description: '1 handful (40g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 278,
    protein: 52.4,
    carbs: 1.8,
    fat: 7.2,
    fiber: 0.4,
  },
  {
    name: 'Droëwors (South African Dried Spiced Beef Sausage with Cloves & Vinegar)',
    category: 'Meat and Poultry',
    portion_description: '2 sticks (50g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 436,
    protein: 41.8,
    carbs: 2.1,
    fat: 29.4,
    fiber: 0.6,
  },
  {
    name: 'South African Boerewors (Traditional Spiced Beef & Pork Sausage, Braaied)',
    category: 'Meat and Poultry',
    portion_description: '1 wheel piece (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 312,
    protein: 17.8,
    carbs: 2.4,
    fat: 26.2,
    fiber: 0.4,
  },
  {
    name: 'Bobotie (South African Spiced Minced Meat Bake with Golden Savoury Egg Custard)',
    category: 'Meat and Poultry',
    portion_description: '1 slice / serving (220g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 204,
    protein: 13.8,
    carbs: 11.6,
    fat: 11.4,
    fiber: 1.8,
  },
  {
    name: 'Chakalaka (Spicy South African Braai Relish with Baked Beans, Peppers & Carrots)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 84,
    protein: 3.2,
    carbs: 12.8,
    fat: 2.4,
    fiber: 3.6,
  },
  {
    name: 'Stiff Pap / Mieliepap (Traditional South African White Maize Porridge, Cooked)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 portion (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 112,
    protein: 2.4,
    carbs: 24.2,
    fat: 0.4,
    fiber: 1.6,
  },
  {
    name: 'South African Ostrich Steak (Ultra-Lean Fillet, Grilled Medium)',
    category: 'Meat and Poultry',
    portion_description: '1 steak (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 122,
    protein: 26.8,
    carbs: 0,
    fat: 1.6,
    fiber: 0,
  },
  {
    name: 'Cape Snoek (Thyrsites atun, Braaied with Apricot Jam & Butter Glaze)',
    category: 'Fish and Seafood',
    portion_description: '1 serving (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 186,
    protein: 22.4,
    carbs: 4.8,
    fat: 8.6,
    fiber: 0,
  },
  {
    name: 'Malva Pudding (South African Caramelized Apricot Sponge with Cream Sauce)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 serving with sauce (140g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 348,
    protein: 4.2,
    carbs: 52.6,
    fat: 14.0,
    fiber: 0.8,
  },
  {
    name: 'Rooibos Tea (Aspalathus linearis, Pure Red Bush Herbal Infusion, No Milk/Sugar)',
    category: 'Dairy and Beverages',
    portion_description: '1 mug (250ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 1,
    protein: 0.1,
    carbs: 0.2,
    fat: 0,
    fiber: 0,
  },
];

// ============================================================================
// 6. SINGAPORE FOOD INSIGHTS DATABASE (HPB Singapore)
// ============================================================================
const singaporeFoods = [
  {
    name: 'Singapore Hainanese Chicken Rice (Poached Chicken with Seasoned Rice & Chili Garlic Dip)',
    category: 'Chicken and Poultry',
    portion_description: '1 plate (320g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 184,
    protein: 9.8,
    carbs: 21.4,
    fat: 6.8,
    fiber: 0.8,
  },
  {
    name: 'Bak Kut Teh (Teochew-Style Peppery Pork Rib Broth with Garlic & Pepper)',
    category: 'Meat and Poultry',
    portion_description: '1 bowl with ribs (300g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 118,
    protein: 12.6,
    carbs: 1.8,
    fat: 6.9,
    fiber: 0.4,
  },
  {
    name: 'Singapore Chilli Crab (Mud Crab in Sweet-Savory Eggy Tomato Chili Gravy)',
    category: 'Fish and Seafood',
    portion_description: '1 serving (300g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 138,
    protein: 14.8,
    carbs: 8.6,
    fat: 5.2,
    fiber: 1.1,
  },
  {
    name: 'Kaya Butter Toast (Toasted Charcoal Bread with Butter & Pandan Coconut Jam)',
    category: 'Breakfast foods',
    portion_description: '2 slices (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 338,
    protein: 5.8,
    carbs: 48.2,
    fat: 14.2,
    fiber: 1.8,
  },
  {
    name: 'Chai Tow Kway / Fried Carrot Cake (Fried Daikon Radish Cake with Egg, Garlic & Sweet Soy)',
    category: 'Snacks and Chaat',
    portion_description: '1 plate (220g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 178,
    protein: 5.2,
    carbs: 23.4,
    fat: 7.4,
    fiber: 1.8,
  },
  {
    name: 'Singapore Kopi (Traditional Robusta Coffee with Sweetened Condensed Milk)',
    category: 'Dairy and Beverages',
    portion_description: '1 cup (200ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 68,
    protein: 1.8,
    carbs: 11.2,
    fat: 1.8,
    fiber: 0,
  },
];

// ============================================================================
// 7. THAI FOOD COMPOSITION DATABASE (INMU Mahidol University)
// ============================================================================
const thaiFoods = [
  {
    name: 'Tom Yum Goong (Thai Spicy & Sour Lemongrass Prawn Soup with Mushrooms & Galangal)',
    category: 'Fish and Seafood',
    portion_description: '1 bowl (300g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 62,
    protein: 7.8,
    carbs: 3.4,
    fat: 1.9,
    fiber: 0.9,
  },
  {
    name: 'Pad Thai (Stir-Fried Rice Noodles with Prawns, Tofu, Peanuts, Egg & Bean Sprouts)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 plate (280g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 178,
    protein: 7.2,
    carbs: 24.6,
    fat: 5.9,
    fiber: 2.1,
  },
  {
    name: 'Thai Green Curry / Gaeng Keow Wan Gai (Chicken with Thai Eggplant in Coconut Green Curry)',
    category: 'Chicken and Poultry',
    portion_description: '1 bowl (250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 154,
    protein: 10.8,
    carbs: 4.8,
    fat: 10.4,
    fiber: 1.8,
  },
  {
    name: 'Som Tum (Thai Green Papaya Salad with Lime, Fish Sauce, Garlic, Chili & Peanuts)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 plate (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 78,
    protein: 3.1,
    carbs: 11.4,
    fat: 2.6,
    fiber: 2.8,
  },
  {
    name: 'Massaman Curry (Thai Mild Peanut Curry with Chicken, Potatoes & Spices in Coconut Milk)',
    category: 'Chicken and Poultry',
    portion_description: '1 bowl (250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 174,
    protein: 10.2,
    carbs: 8.6,
    fat: 11.2,
    fiber: 1.8,
  },
  {
    name: 'Tom Kha Gai (Thai Coconut Galangal Chicken Soup with Kaffir Lime)',
    category: 'Chicken and Poultry',
    portion_description: '1 bowl (250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 128,
    protein: 8.4,
    carbs: 3.6,
    fat: 9.1,
    fiber: 0.8,
  },
  {
    name: 'Mango Sticky Rice / Khao Niew Mamuang (Sweet Coconut Sticky Rice with Ripe Mango)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 plate (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 198,
    protein: 2.8,
    carbs: 36.4,
    fat: 4.9,
    fiber: 1.6,
  },
  {
    name: 'Pad Krapow Gai (Thai Spicy Holy Basil Minced Chicken Stir-Fry with Chili & Garlic)',
    category: 'Chicken and Poultry',
    portion_description: '1 portion (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 168,
    protein: 18.2,
    carbs: 4.2,
    fat: 8.9,
    fiber: 1.1,
  },
  {
    name: 'Thai Iced Tea / Cha Yen (Spiced Black Tea with Sweetened Condensed Milk)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (250ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 74,
    protein: 1.6,
    carbs: 13.2,
    fat: 1.7,
    fiber: 0,
  },
];

// ============================================================================
// 8. VIETNAMESE FOOD COMPOSITION TABLE (NIN Vietnam)
// ============================================================================
const vietnameseFoods = [
  {
    name: 'Phở Bò (Traditional Vietnamese Beef Noodle Soup with Star Anise & Fresh Herbs)',
    category: 'Meat and Poultry',
    portion_description: '1 large bowl (400g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 92,
    protein: 6.8,
    carbs: 12.4,
    fat: 1.8,
    fiber: 0.8,
  },
  {
    name: 'Phở Gà (Vietnamese Chicken Noodle Soup with Ginger & Herbs)',
    category: 'Chicken and Poultry',
    portion_description: '1 large bowl (400g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 86,
    protein: 6.4,
    carbs: 12.2,
    fat: 1.4,
    fiber: 0.7,
  },
  {
    name: 'Bánh Mì Thịt (Vietnamese Baguette with Pork Pâté, Cold Cuts, Pickled Daikon & Cilantro)',
    category: 'Meat and Poultry',
    portion_description: '1 sandwich (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 248,
    protein: 11.4,
    carbs: 29.8,
    fat: 9.4,
    fiber: 2.1,
  },
  {
    name: 'Gỏi Cuốn (Vietnamese Fresh Spring Rolls with Prawns, Pork, Herbs & Rice Vermicelli)',
    category: 'Snacks and Chaat',
    portion_description: '2 rolls (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 124,
    protein: 7.8,
    carbs: 19.4,
    fat: 1.8,
    fiber: 1.2,
  },
  {
    name: 'Bún Chả (Hanoi Grilled Pork Meatballs with Rice Vermicelli & Nuoc Cham Sauce)',
    category: 'Meat and Poultry',
    portion_description: '1 serving (300g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 168,
    protein: 11.8,
    carbs: 18.2,
    fat: 5.4,
    fiber: 1.4,
  },
  {
    name: 'Cà Phê Sữa Đá (Vietnamese Dark Roast Drip Coffee with Sweetened Condensed Milk over Ice)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (200ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 84,
    protein: 2.1,
    carbs: 14.8,
    fat: 1.9,
    fiber: 0,
  },
];

// ============================================================================
// 9. CHINA FOOD COMPOSITION TABLE (NINH / CDC China)
// ============================================================================
const chinaFoods = [
  {
    name: 'Peking Roasted Duck (Crispy Skin & Tender Meat)',
    category: 'Meat and Poultry',
    portion_description: '1 portion (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 337,
    protein: 19.2,
    carbs: 0,
    fat: 28.9,
    fiber: 0,
  },
  {
    name: 'Kung Pao Chicken / Gong Bao Ji Ding (Diced Chicken with Peanuts, Chili & Sichuan Pepper)',
    category: 'Chicken and Poultry',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 188,
    protein: 16.4,
    carbs: 6.8,
    fat: 10.8,
    fiber: 1.8,
  },
  {
    name: 'Mapo Tofu (Sichuan Spicy Braised Tofu with Minced Pork & Doubanjiang Fermented Bean Paste)',
    category: 'Vegetarian Curries and Paneer',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 136,
    protein: 9.8,
    carbs: 4.6,
    fat: 8.9,
    fiber: 1.4,
  },
  {
    name: 'Har Gow (Cantonese Steamed Translucent Shrimp Dumplings)',
    category: 'Snacks and Chaat',
    portion_description: '4 dumplings (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 162,
    protein: 9.4,
    carbs: 22.8,
    fat: 3.8,
    fiber: 1.2,
  },
  {
    name: 'Siu Mai / Shumai (Steamed Pork & Shrimp Dumplings in Wonton Wrapper)',
    category: 'Snacks and Chaat',
    portion_description: '4 dumplings (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 214,
    protein: 12.8,
    carbs: 14.6,
    fat: 11.6,
    fiber: 0.8,
  },
  {
    name: 'Xiao Long Bao (Shanghainese Steamed Pork Soup Dumplings)',
    category: 'Snacks and Chaat',
    portion_description: '4 dumplings (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 198,
    protein: 10.2,
    carbs: 18.6,
    fat: 9.2,
    fiber: 0.6,
  },
  {
    name: 'Cantonese Char Siu (Honey Glazed BBQ Roast Pork Loin)',
    category: 'Meat and Poultry',
    portion_description: '1 portion (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 264,
    protein: 23.4,
    carbs: 8.8,
    fat: 14.8,
    fiber: 0.4,
  },
  {
    name: 'Bok Choy / Chinese White Cabbage (Brassica rapa subsp. chinensis, Steamed)',
    category: 'Green Leafy Vegetables',
    portion_description: '1 cup steamed (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 13,
    protein: 1.5,
    carbs: 2.2,
    fat: 0.2,
    fiber: 1.0,
  },
  {
    name: 'Gai Lan / Chinese Broccoli (Brassica oleracea var. alboglabra, Steamed with Oyster Sauce)',
    category: 'Green Leafy Vegetables',
    portion_description: '1 plate (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 34,
    protein: 2.4,
    carbs: 4.8,
    fat: 0.6,
    fiber: 2.8,
  },
  {
    name: 'Century Egg / Pidan (Preserved Duck Egg in Clay & Wood Ash)',
    category: 'Egg Dishes',
    portion_description: '1 egg (60g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 185,
    protein: 13.8,
    carbs: 1.2,
    fat: 14.2,
    fiber: 0,
  },
];

// ============================================================================
// 10. PHILIPPINE FOOD COMPOSITION TABLES (FNRI - DOST)
// ============================================================================
const philippineFoods = [
  {
    name: 'Chicken and Pork Adobo (Braised in Soy Sauce, Cane Vinegar, Garlic & Black Peppercorns)',
    category: 'Meat and Poultry',
    portion_description: '1 serving (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 198,
    protein: 19.4,
    carbs: 3.6,
    fat: 11.8,
    fiber: 0.4,
  },
  {
    name: 'Sinigang na Baboy (Filipino Sour Tamarind Pork Soup with Water Spinach & Radish)',
    category: 'Meat and Poultry',
    portion_description: '1 bowl (300g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 114,
    protein: 10.8,
    carbs: 3.8,
    fat: 6.2,
    fiber: 1.4,
  },
  {
    name: 'Kare-Kare (Filipino Oxtail, Beef Tripe & Eggplant Stew in Savoury Peanut Sauce)',
    category: 'Meat and Poultry',
    portion_description: '1 serving (250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 218,
    protein: 16.4,
    carbs: 6.8,
    fat: 14.2,
    fiber: 2.1,
  },
  {
    name: 'Pancit Bihon Guisado (Stir-Fried Rice Vermicelli with Chicken, Shrimp, Cabbage & Calamansi)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 plate (220g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 164,
    protein: 7.2,
    carbs: 24.8,
    fat: 4.2,
    fiber: 1.8,
  },
  {
    name: 'Lumpia Shanghai (Crispy Golden Fried Pork Spring Rolls with Sweet Chili Sauce)',
    category: 'Snacks and Chaat',
    portion_description: '4 pieces (80g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 284,
    protein: 12.6,
    carbs: 21.4,
    fat: 16.8,
    fiber: 1.1,
  },
  {
    name: 'Bangus / Philippine Milkfish (Chanos chanos, Marinated in Vinegar & Garlic, Fried)',
    category: 'Fish and Seafood',
    portion_description: '1 fillet (140g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 198,
    protein: 24.2,
    carbs: 1.2,
    fat: 10.8,
    fiber: 0,
  },
  {
    name: 'Sizzling Pork Sisig (Minced Pork Jowl & Liver Seasoned with Calamansi, Onion & Chili)',
    category: 'Meat and Poultry',
    portion_description: '1 serving (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 278,
    protein: 18.6,
    carbs: 2.8,
    fat: 21.4,
    fiber: 0.6,
  },
  {
    name: 'Halo-Halo (Filipino Shaved Ice Dessert with Sweet Beans, Ube Halaya, Leche Flan & Milk)',
    category: 'Indian Sweets and Mithai',
    portion_description: '1 tall glass (280g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 154,
    protein: 3.4,
    carbs: 28.6,
    fat: 3.1,
    fiber: 2.2,
  },
];

// ============================================================================
// 11. TürKomp - Turkish Food Composition Database (TÜBİTAK MAM)
// ============================================================================
const turKompFoods = [
  {
    name: 'Turkish Döner Kebab (Thinly Sliced Spit-Roasted Marinated Beef & Lamb)',
    category: 'Meat and Poultry',
    portion_description: '1 portion (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 236,
    protein: 21.8,
    carbs: 2.4,
    fat: 15.6,
    fiber: 0.4,
  },
  {
    name: 'Adana Kebab (Hand-Minced Spicy Lamb Skewer Cooked over Charcoal)',
    category: 'Meat and Poultry',
    portion_description: '1 skewer (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 258,
    protein: 19.4,
    carbs: 2.8,
    fat: 18.8,
    fiber: 0.8,
  },
  {
    name: 'Lahmacun (Turkish Crispy Thin Flatbread Topped with Minced Lamb, Tomato & Herbs)',
    category: 'Baked Products',
    portion_description: '1 lahmacun (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 228,
    protein: 9.8,
    carbs: 29.4,
    fat: 8.2,
    fiber: 2.4,
  },
  {
    name: 'Menemen (Turkish Scrambled Eggs with Tomatoes, Green Peppers & Olive Oil)',
    category: 'Egg Dishes',
    portion_description: '1 skillet serving (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 124,
    protein: 6.8,
    carbs: 4.8,
    fat: 8.6,
    fiber: 1.6,
  },
  {
    name: 'Mercimek Çorbası (Traditional Turkish Red Lentil Soup with Cumin & Lemon)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 bowl (250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 88,
    protein: 5.2,
    carbs: 12.8,
    fat: 2.1,
    fiber: 3.2,
  },
  {
    name: 'Turkish Mantı (Tiny Spiced Beef Dumplings with Garlic Yogurt Sauce & Sumac Butter)',
    category: 'Meat and Poultry',
    portion_description: '1 plate (220g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 198,
    protein: 9.4,
    carbs: 24.6,
    fat: 7.2,
    fiber: 1.8,
  },
  {
    name: 'Turkish Ayran (Traditional Chilled Salted Frothy Yogurt Drink)',
    category: 'Dairy and Beverages',
    portion_description: '1 glass (200ml)',
    base_amount: 100,
    base_unit: 'g',
    calories: 38,
    protein: 2.1,
    carbs: 2.8,
    fat: 1.9,
    fiber: 0,
  },
  {
    name: 'Gaziantep Pistachio Baklava (Multi-Layered Filo Pastry with Crushed Pistachios & Syrup)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2 pieces (60g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 428,
    protein: 6.8,
    carbs: 52.4,
    fat: 21.8,
    fiber: 2.4,
  },
  {
    name: 'Simit / Turkish Sesame Bagel (Circular Molasses-Dipped Bread with Sesame Seeds)',
    category: 'Baked Products',
    portion_description: '1 simit (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 312,
    protein: 9.6,
    carbs: 54.8,
    fat: 6.4,
    fiber: 3.8,
  },
];

// ============================================================================
// 12. TUNISIAN FOOD COMPOSITION DATABASE (INNTA)
// ============================================================================
const tunisianFoods = [
  {
    name: 'Tunisian Couscous with Lamb, Chickpeas & Vegetables (Steamed Semolina Stew)',
    category: 'Meat and Poultry',
    portion_description: '1 plate (300g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 168,
    protein: 9.2,
    carbs: 22.4,
    fat: 4.8,
    fiber: 3.1,
  },
  {
    name: 'Shakshuka (North African Poached Eggs in Spicy Tomato, Red Pepper & Cumin Sauce)',
    category: 'Egg Dishes',
    portion_description: '1 skillet portion (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 112,
    protein: 6.4,
    carbs: 6.2,
    fat: 7.2,
    fiber: 2.1,
  },
  {
    name: 'Lablabi (Tunisian Spiced Chickpea Soup with Cumin, Garlic, Olive Oil & Crusty Bread)',
    category: 'Dal and Lentil Dishes',
    portion_description: '1 bowl (280g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 142,
    protein: 6.8,
    carbs: 21.6,
    fat: 3.4,
    fiber: 5.6,
  },
  {
    name: 'Brik à l’Oeuf (Tunisian Crispy Thin Pastry Pocket with Whole Egg, Tuna, Parsley & Harissa)',
    category: 'Snacks and Chaat',
    portion_description: '1 brik (110g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 254,
    protein: 13.8,
    carbs: 18.2,
    fat: 14.6,
    fiber: 1.2,
  },
  {
    name: 'Tunisian Harissa Paste (Roasted Red Baklouti Chili, Garlic, Caraway & Olive Oil)',
    category: 'Condiments and Spices',
    portion_description: '1 tablespoon (15g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 118,
    protein: 3.2,
    carbs: 12.4,
    fat: 6.2,
    fiber: 4.8,
  },
  {
    name: 'Makroudh (Traditional North African Semolina Pastry Stuffed with Date Paste & Dipped in Honey)',
    category: 'Indian Sweets and Mithai',
    portion_description: '2 pieces (60g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 386,
    protein: 4.6,
    carbs: 68.4,
    fat: 11.2,
    fiber: 3.6,
  },
];

// ============================================================================
// 13. KENYA FOOD COMPOSITION TABLES (MOH Kenya / FAO)
// ============================================================================
const kenyanFoods = [
  {
    name: 'Kenyan Ugali (Traditional Stiff White Maize Flour Porridge, Cooked)',
    category: 'Rice and Grain Dishes',
    portion_description: '1 portion (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 118,
    protein: 2.6,
    carbs: 25.4,
    fat: 0.5,
    fiber: 1.8,
  },
  {
    name: 'Sukuma Wiki (Kenyan Braised Collard Greens with Onions, Tomatoes & Spices)',
    category: 'Green Leafy Vegetables',
    portion_description: '1 medium bowl (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 58,
    protein: 2.8,
    carbs: 6.4,
    fat: 2.6,
    fiber: 3.4,
  },
  {
    name: 'Nyama Choma (Kenyan Roasted Goat Meat Seasoned with Salt over Open Charcoal)',
    category: 'Meat and Poultry',
    portion_description: '1 serving (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 218,
    protein: 27.4,
    carbs: 0,
    fat: 12.2,
    fiber: 0,
  },
  {
    name: 'Githeri (Kenyan Boiled Whole Maize & Red Kidney Beans Stew with Vegetables)',
    category: 'Grain Legumes and Pulses',
    portion_description: '1 bowl (220g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 146,
    protein: 6.8,
    carbs: 25.6,
    fat: 1.8,
    fiber: 6.4,
  },
  {
    name: 'Irio / Mukimo (Kenyan Mashed Potatoes with Green Peas, Corn & Pumpkin Leaves)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 medium bowl (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 114,
    protein: 3.8,
    carbs: 22.8,
    fat: 1.2,
    fiber: 3.8,
  },
  {
    name: 'Kenyan Chapati (Soft Layered Pan-Fried Whole Wheat Flatbread with Oil)',
    category: 'Roti and Indian Breads',
    portion_description: '1 chapati (70g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 308,
    protein: 7.8,
    carbs: 48.2,
    fat: 9.8,
    fiber: 5.6,
  },
  {
    name: 'Mandazi / Mahamri (Swahili Spiced Coconut & Cardamom Fried Bread Doughnut)',
    category: 'Baked Products',
    portion_description: '1 mandazi (50g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 342,
    protein: 6.4,
    carbs: 52.8,
    fat: 12.4,
    fiber: 2.1,
  },
  {
    name: 'Kachumbari (East African Fresh Diced Tomato, Red Onion, Cilantro & Lime Salad)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 bowl (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 32,
    protein: 1.1,
    carbs: 6.8,
    fat: 0.3,
    fiber: 1.8,
  },
];

// ============================================================================
// 14. UGANDA FOOD COMPOSITION TABLE (MAAIF / FAO)
// ============================================================================
const ugandanFoods = [
  {
    name: 'Matooke (Ugandan Steamed Green Cooking Bananas / Plantains, Mashed)',
    category: 'Vegetables and Sabzi',
    portion_description: '1 portion (200g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 122,
    protein: 1.3,
    carbs: 29.6,
    fat: 0.3,
    fiber: 2.3,
  },
  {
    name: 'Ugandan Rolex (Street Food Rolled Chapati with Fried Two-Egg Vegetable Omelette)',
    category: 'Breakfast foods',
    portion_description: '1 rolex (180g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 246,
    protein: 9.8,
    carbs: 28.4,
    fat: 10.8,
    fiber: 2.4,
  },
  {
    name: 'Chicken Luwombo (Ugandan Traditional Stewed Chicken in Rich Peanut Sauce Steamed in Banana Leaves)',
    category: 'Chicken and Poultry',
    portion_description: '1 pouch serving (250g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 184,
    protein: 17.2,
    carbs: 4.8,
    fat: 10.8,
    fiber: 1.6,
  },
  {
    name: 'Ugandan Groundnut Sauce / G-Nut Paste (Smooth Peanut & Sesame Puree Sauce for Matooke)',
    category: 'Grain Legumes and Pulses',
    portion_description: '1/2 cup sauce (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 286,
    protein: 12.8,
    carbs: 11.4,
    fat: 22.6,
    fiber: 4.2,
  },
  {
    name: 'Lake Victoria Nile Perch Fillet (Lates niloticus, Grilled Flesh)',
    category: 'Fish and Seafood',
    portion_description: '1 fillet (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 128,
    protein: 22.4,
    carbs: 0,
    fat: 4.2,
    fiber: 0,
  },
];

// ============================================================================
// 15. FAO/INFOODS GLOBAL FOOD COMPOSITION DATABASES (uFiSh, BioFoodComp, AnFooD)
// ============================================================================
const faoInfoodsGlobal = [
  {
    name: 'Antarctic Krill (Euphausia superba, Whole Raw / Meat)',
    category: 'Fish and Seafood',
    portion_description: '1 portion (100g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 86,
    protein: 15.4,
    carbs: 0.6,
    fat: 2.4,
    fiber: 0,
  },
  {
    name: 'African Sharptooth Catfish (Clarias gariepinus, Baked Fillet)',
    category: 'Fish and Seafood',
    portion_description: '1 fillet (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 118,
    protein: 19.8,
    carbs: 0,
    fat: 4.2,
    fiber: 0,
  },
  {
    name: 'Nile Tilapia (Oreochromis niloticus, Wild Caught, Steamed Fillet)',
    category: 'Fish and Seafood',
    portion_description: '1 fillet (140g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 96,
    protein: 20.1,
    carbs: 0,
    fat: 1.7,
    fiber: 0,
  },
  {
    name: 'Atlantic Cod Liver (Gadus morhua, Canned in Own Oil)',
    category: 'Fish and Seafood',
    portion_description: '1 can drained (120g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 612,
    protein: 4.8,
    carbs: 0.4,
    fat: 66.2,
    fiber: 0,
  },
  {
    name: 'European Sea Bass / Branzino (Dicentrarchus labrax, Baked Fillet)',
    category: 'Fish and Seafood',
    portion_description: '1 fillet (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 124,
    protein: 23.6,
    carbs: 0,
    fat: 3.2,
    fiber: 0,
  },
  {
    name: 'Yellowfin Tuna (Thunnus albacares, Fresh Raw Loin Steak)',
    category: 'Fish and Seafood',
    portion_description: '1 steak (160g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 109,
    protein: 24.4,
    carbs: 0,
    fat: 0.6,
    fiber: 0,
  },
  {
    name: 'Pacific Halibut (Hippoglossus stenolepis, Broiled Fillet)',
    category: 'Fish and Seafood',
    portion_description: '1 fillet (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 140,
    protein: 26.7,
    carbs: 0,
    fat: 2.9,
    fiber: 0,
  },
  {
    name: 'Red Snapper (Lutjanus campechanus, Baked Fillet)',
    category: 'Fish and Seafood',
    portion_description: '1 fillet (150g)',
    base_amount: 100,
    base_unit: 'g',
    calories: 128,
    protein: 26.3,
    carbs: 0,
    fat: 1.7,
    fiber: 0,
  },
];

async function seedAll15Databases() {
  console.log('================================================================');
  console.log('VITALIS: SEEDING 15 GLOBAL FOOD-COMPOSITION DATABASES');
  console.log('1. TBCA (Brazil)');
  console.log('2. MEXT Japan (Japan 8th Edition)');
  console.log('3. MyFCD (Malaysia)');
  console.log('4. FOODfiles (New Zealand)');
  console.log('5. SAFOODS (South Africa)');
  console.log('6. Singapore Food Insights (Singapore)');
  console.log('7. Thai FCD (Thailand)');
  console.log('8. Vietnamese FCT (Vietnam)');
  console.log('9. China FCT (China)');
  console.log('10. Philippine FCT (Philippines)');
  console.log('11. TürKomp (Turkey)');
  console.log('12. Tunisian FCD (Tunisia)');
  console.log('13. Kenya FCT (Kenya)');
  console.log('14. Uganda FCT (Uganda)');
  console.log('15. FAO/INFOODS Global (uFiSh, BioFoodComp, AnFooD)');
  console.log('================================================================\n');

  const allCandidates = [
    ...tbcaFoods,
    ...mextJapanFoods,
    ...myFcdFoods,
    ...foodFilesNz,
    ...saFoods,
    ...singaporeFoods,
    ...thaiFoods,
    ...vietnameseFoods,
    ...chinaFoods,
    ...philippineFoods,
    ...turKompFoods,
    ...tunisianFoods,
    ...kenyanFoods,
    ...ugandanFoods,
    ...faoInfoodsGlobal,
  ];

  console.log(`Total candidate global records: ${allCandidates.length}`);

  // Fetch all existing foods from Supabase for deduplication
  let allExisting = [];
  let from = 0;
  const pageSize = 1000;
  while (true) {
    const { data: batch, error: fetchErr } = await supabase
      .from('foods')
      .select('name')
      .range(from, from + pageSize - 1);

    if (fetchErr) {
      console.error('❌ Error fetching existing foods:', fetchErr);
      return;
    }
    allExisting = allExisting.concat(batch || []);
    if (!batch || batch.length < pageSize) break;
    from += pageSize;
  }

  const existingNames = new Set((allExisting || []).map(r => r.name.toLowerCase().trim()));
  console.log(`Found ${existingNames.size} existing foods in Vitalis database.`);

  const toInsert = [];
  const skipped = [];

  for (const food of allCandidates) {
    const key = food.name.toLowerCase().trim();
    if (existingNames.has(key)) {
      skipped.push(food.name);
    } else {
      toInsert.push({
        name: food.name,
        category: food.category,
        portion_description: food.portion_description,
        base_amount: food.base_amount,
        base_unit: food.base_unit,
        calories: food.calories,
        protein: food.protein,
        carbs: food.carbs,
        fat: food.fat,
        fiber: food.fiber,
        user_id: null,
      });
      existingNames.add(key);
    }
  }

  console.log(`\nReady to insert: ${toInsert.length} new unique global foods.`);
  console.log(`Skipped duplicates: ${skipped.length} foods.`);

  // Write SQL migration
  const migrationPath = path.join(__dirname, '../../supabase/migrations/20260907000007_seed_15_global_food_databases.sql');
  let sqlContent = `-- ==============================================================================\n`;
  sqlContent += `-- VITALIS FOOD DATABASE: 15 GLOBAL FOOD-COMPOSITION DATABASES SEED\n`;
  sqlContent += `-- Sources:\n`;
  sqlContent += `-- 1. TBCA - Brazilian Food Composition Table (USP / FoRC)\n`;
  sqlContent += `-- 2. Japanese Standard Tables of Food Composition (MEXT Japan 8th Edition)\n`;
  sqlContent += `-- 3. MyFCD - Malaysian Food Composition Database (MOH Malaysia)\n`;
  sqlContent += `-- 4. FOODfiles - New Zealand Food Composition Database (Plant & Food Research)\n`;
  sqlContent += `-- 5. SAFOODS - South African Food Data System (SAMRC)\n`;
  sqlContent += `-- 6. Singapore Food Insights Database (HPB / SFA Singapore)\n`;
  sqlContent += `-- 7. Thai Food Composition Database (INMU Mahidol University)\n`;
  sqlContent += `-- 8. Vietnamese Food Composition Table (NIN Vietnam)\n`;
  sqlContent += `-- 9. China Food Composition Table (NINH / CDC China)\n`;
  sqlContent += `-- 10. Philippine Food Composition Tables (FNRI - DOST)\n`;
  sqlContent += `-- 11. TürKomp - Turkish Food Composition Database (TÜBİTAK MAM)\n`;
  sqlContent += `-- 12. Tunisian Food Composition Database (INNTA)\n`;
  sqlContent += `-- 13. Kenya Food Composition Tables (MOH Kenya / FAO)\n`;
  sqlContent += `-- 14. Uganda Food Composition Table (MAAIF / FAO)\n`;
  sqlContent += `-- 15. FAO/INFOODS Global Food Composition Databases (uFiSh, BioFoodComp, AnFooD)\n`;
  sqlContent += `-- Total unique records: ${toInsert.length}\n`;
  sqlContent += `-- User ID: NULL (System Food reference catalog)\n`;
  sqlContent += `-- ==============================================================================\n\n`;
  sqlContent += `INSERT INTO public.foods (name, category, portion_description, base_amount, base_unit, calories, protein, carbs, fat, fiber, user_id) VALUES\n`;

  const valueRows = toInsert.map(f => {
    const nameEsc = f.name.replace(/'/g, "''");
    const catEsc = f.category.replace(/'/g, "''");
    const portionEsc = f.portion_description.replace(/'/g, "''");
    return `  ('${nameEsc}', '${catEsc}', '${portionEsc}', ${f.base_amount}, '${f.base_unit}', ${f.calories}, ${f.protein}, ${f.carbs}, ${f.fat}, ${f.fiber}, NULL)`;
  });

  sqlContent += valueRows.join(',\n') + ';\n';

  fs.writeFileSync(migrationPath, sqlContent, 'utf8');
  console.log(`\n✅ Generated migration SQL file: ${migrationPath}`);
}

seedAll15Databases();
